/**
 * Tập chữ ứng viên cho nhận dạng viết tay.
 *
 * Phạm vi: chữ cảm xúc của MandoMood + HSK1 thường gặp + số + một số chữ phổ
 * biến. Dữ liệu nét của từng chữ được tải runtime từ hanzi-writer (MIT).
 * Mở rộng danh sách này = mở rộng khả năng nhận dạng (đánh đổi tốc độ tải).
 */

export interface CandidateInfo {
  char: string;
  pinyin: string;
  meaning: string;
}

export const HANDWRITING_CANDIDATES: CandidateInfo[] = [
  // ── Chữ cảm xúc (đồng bộ /characters) ──
  { char: "爱", pinyin: "ài", meaning: "tình yêu" },
  { char: "心", pinyin: "xīn", meaning: "trái tim" },
  { char: "情", pinyin: "qíng", meaning: "tình cảm" },
  { char: "念", pinyin: "niàn", meaning: "nỗi nhớ" },
  { char: "惜", pinyin: "xī", meaning: "tiếc thương" },
  { char: "暖", pinyin: "nuǎn", meaning: "ấm áp" },
  { char: "缘", pinyin: "yuán", meaning: "duyên phận" },
  { char: "梦", pinyin: "mèng", meaning: "giấc mơ" },
  { char: "望", pinyin: "wàng", meaning: "trông mong" },
  { char: "盼", pinyin: "pàn", meaning: "mong chờ" },
  { char: "归", pinyin: "guī", meaning: "trở về" },
  { char: "泪", pinyin: "lèi", meaning: "nước mắt" },
  { char: "别", pinyin: "bié", meaning: "chia tay" },
  { char: "痛", pinyin: "tòng", meaning: "đau" },
  { char: "散", pinyin: "sàn", meaning: "tan biến" },
  { char: "孤", pinyin: "gū", meaning: "cô đơn" },
  { char: "哭", pinyin: "kū", meaning: "khóc" },
  { char: "静", pinyin: "jìng", meaning: "bình yên" },
  { char: "思", pinyin: "sī", meaning: "suy nghĩ" },
  { char: "寂", pinyin: "jì", meaning: "cô tịch" },
  { char: "真", pinyin: "zhēn", meaning: "chân thật" },
  { char: "忍", pinyin: "rěn", meaning: "nhẫn nại" },
  { char: "勇", pinyin: "yǒng", meaning: "dũng cảm" },
  { char: "笑", pinyin: "xiào", meaning: "nụ cười" },
  { char: "懂", pinyin: "dǒng", meaning: "thấu hiểu" },
  { char: "陪", pinyin: "péi", meaning: "đồng hành" },
  { char: "美", pinyin: "měi", meaning: "vẻ đẹp" },
  { char: "悟", pinyin: "wù", meaning: "giác ngộ" },
  { char: "福", pinyin: "fú", meaning: "hạnh phúc" },

  // ── Số ──
  { char: "一", pinyin: "yī", meaning: "một" },
  { char: "二", pinyin: "èr", meaning: "hai" },
  { char: "三", pinyin: "sān", meaning: "ba" },
  { char: "四", pinyin: "sì", meaning: "bốn" },
  { char: "五", pinyin: "wǔ", meaning: "năm" },
  { char: "六", pinyin: "liù", meaning: "sáu" },
  { char: "七", pinyin: "qī", meaning: "bảy" },
  { char: "八", pinyin: "bā", meaning: "tám" },
  { char: "九", pinyin: "jiǔ", meaning: "chín" },
  { char: "十", pinyin: "shí", meaning: "mười" },

  // ── HSK1 / thường gặp ──
  { char: "我", pinyin: "wǒ", meaning: "tôi" },
  { char: "你", pinyin: "nǐ", meaning: "bạn" },
  { char: "他", pinyin: "tā", meaning: "anh ấy" },
  { char: "她", pinyin: "tā", meaning: "cô ấy" },
  { char: "好", pinyin: "hǎo", meaning: "tốt" },
  { char: "是", pinyin: "shì", meaning: "là" },
  { char: "不", pinyin: "bù", meaning: "không" },
  { char: "人", pinyin: "rén", meaning: "người" },
  { char: "大", pinyin: "dà", meaning: "to lớn" },
  { char: "小", pinyin: "xiǎo", meaning: "nhỏ" },
  { char: "多", pinyin: "duō", meaning: "nhiều" },
  { char: "少", pinyin: "shǎo", meaning: "ít" },
  { char: "上", pinyin: "shàng", meaning: "trên" },
  { char: "下", pinyin: "xià", meaning: "dưới" },
  { char: "中", pinyin: "zhōng", meaning: "giữa, Trung" },
  { char: "国", pinyin: "guó", meaning: "nước" },
  { char: "日", pinyin: "rì", meaning: "ngày, mặt trời" },
  { char: "月", pinyin: "yuè", meaning: "tháng, mặt trăng" },
  { char: "年", pinyin: "nián", meaning: "năm" },
  { char: "天", pinyin: "tiān", meaning: "trời" },
  { char: "水", pinyin: "shuǐ", meaning: "nước" },
  { char: "火", pinyin: "huǒ", meaning: "lửa" },
  { char: "山", pinyin: "shān", meaning: "núi" },
  { char: "木", pinyin: "mù", meaning: "cây, gỗ" },
  { char: "口", pinyin: "kǒu", meaning: "miệng" },
  { char: "手", pinyin: "shǒu", meaning: "tay" },
  { char: "目", pinyin: "mù", meaning: "mắt" },
  { char: "家", pinyin: "jiā", meaning: "nhà" },
  { char: "学", pinyin: "xué", meaning: "học" },
  { char: "生", pinyin: "shēng", meaning: "sinh, sống" },
  { char: "来", pinyin: "lái", meaning: "đến" },
  { char: "去", pinyin: "qù", meaning: "đi" },
  { char: "吃", pinyin: "chī", meaning: "ăn" },
  { char: "喝", pinyin: "hē", meaning: "uống" },
  { char: "看", pinyin: "kàn", meaning: "nhìn, xem" },
  { char: "听", pinyin: "tīng", meaning: "nghe" },
  { char: "说", pinyin: "shuō", meaning: "nói" },
  { char: "读", pinyin: "dú", meaning: "đọc" },
  { char: "写", pinyin: "xiě", meaning: "viết" },
  { char: "好", pinyin: "hǎo", meaning: "tốt" },
  { char: "今", pinyin: "jīn", meaning: "nay" },
  { char: "明", pinyin: "míng", meaning: "sáng, ngày mai" },
  { char: "白", pinyin: "bái", meaning: "trắng" },
  { char: "黑", pinyin: "hēi", meaning: "đen" },
  { char: "红", pinyin: "hóng", meaning: "đỏ" },
  { char: "花", pinyin: "huā", meaning: "hoa" },
  { char: "雨", pinyin: "yǔ", meaning: "mưa" },
  { char: "风", pinyin: "fēng", meaning: "gió" },
  { char: "云", pinyin: "yún", meaning: "mây" },
  { char: "星", pinyin: "xīng", meaning: "sao" },
  { char: "时", pinyin: "shí", meaning: "thời gian" },
  { char: "光", pinyin: "guāng", meaning: "ánh sáng" },
  { char: "走", pinyin: "zǒu", meaning: "đi bộ" },
  { char: "想", pinyin: "xiǎng", meaning: "nghĩ, muốn" },
  { char: "知", pinyin: "zhī", meaning: "biết" },
  { char: "道", pinyin: "dào", meaning: "đường, đạo" },
  { char: "朋", pinyin: "péng", meaning: "bạn (bè)" },
  { char: "友", pinyin: "yǒu", meaning: "bạn" },

  // ── HSK1 mở rộng (trọn bộ chữ đơn thường gặp) ──
  { char: "的", pinyin: "de", meaning: "(trợ từ sở hữu)" },
  { char: "了", pinyin: "le", meaning: "(trợ từ hoàn thành)" },
  { char: "在", pinyin: "zài", meaning: "ở, đang" },
  { char: "有", pinyin: "yǒu", meaning: "có" },
  { char: "这", pinyin: "zhè", meaning: "này" },
  { char: "那", pinyin: "nà", meaning: "kia" },
  { char: "个", pinyin: "gè", meaning: "(lượng từ) cái" },
  { char: "们", pinyin: "men", meaning: "(số nhiều)" },
  { char: "很", pinyin: "hěn", meaning: "rất" },
  { char: "都", pinyin: "dōu", meaning: "đều" },
  { char: "和", pinyin: "hé", meaning: "và" },
  { char: "会", pinyin: "huì", meaning: "biết, sẽ" },
  { char: "能", pinyin: "néng", meaning: "có thể" },
  { char: "没", pinyin: "méi", meaning: "không (có)" },
  { char: "要", pinyin: "yào", meaning: "muốn, cần" },
  { char: "做", pinyin: "zuò", meaning: "làm" },
  { char: "叫", pinyin: "jiào", meaning: "gọi, tên là" },
  { char: "住", pinyin: "zhù", meaning: "ở, sống" },
  { char: "工", pinyin: "gōng", meaning: "công việc" },
  { char: "作", pinyin: "zuò", meaning: "làm việc" },
  { char: "医", pinyin: "yī", meaning: "y, bác sĩ" },
  { char: "院", pinyin: "yuàn", meaning: "viện" },
  { char: "飞", pinyin: "fēi", meaning: "bay" },
  { char: "机", pinyin: "jī", meaning: "máy" },
  { char: "出", pinyin: "chū", meaning: "ra" },
  { char: "车", pinyin: "chē", meaning: "xe" },
  { char: "北", pinyin: "běi", meaning: "bắc" },
  { char: "京", pinyin: "jīng", meaning: "kinh đô" },
  { char: "块", pinyin: "kuài", meaning: "đồng (tiền)" },
  { char: "钱", pinyin: "qián", meaning: "tiền" },
  { char: "谢", pinyin: "xiè", meaning: "cảm ơn" },
  { char: "对", pinyin: "duì", meaning: "đúng, đối với" },
  { char: "起", pinyin: "qǐ", meaning: "dậy, lên" },
  { char: "请", pinyin: "qǐng", meaning: "mời, xin" },
  { char: "问", pinyin: "wèn", meaning: "hỏi" },
  { char: "名", pinyin: "míng", meaning: "tên" },
  { char: "字", pinyin: "zì", meaning: "chữ" },
  { char: "几", pinyin: "jǐ", meaning: "mấy" },
  { char: "号", pinyin: "hào", meaning: "số, ngày" },
  { char: "期", pinyin: "qī", meaning: "kỳ" },
  { char: "昨", pinyin: "zuó", meaning: "hôm qua" },
  { char: "现", pinyin: "xiàn", meaning: "hiện tại" },
  { char: "点", pinyin: "diǎn", meaning: "giờ, điểm" },
  { char: "分", pinyin: "fēn", meaning: "phút, phân" },
  { char: "些", pinyin: "xiē", meaning: "một số" },
  { char: "杯", pinyin: "bēi", meaning: "ly, cốc" },
  { char: "茶", pinyin: "chá", meaning: "trà" },
  { char: "苹", pinyin: "píng", meaning: "(táo) bình" },
  { char: "果", pinyin: "guǒ", meaning: "quả" },
  { char: "菜", pinyin: "cài", meaning: "rau, món ăn" },
  { char: "米", pinyin: "mǐ", meaning: "gạo, mét" },
  { char: "饭", pinyin: "fàn", meaning: "cơm" },
  { char: "书", pinyin: "shū", meaning: "sách" },
  { char: "本", pinyin: "běn", meaning: "(lượng từ) quyển" },
  { char: "校", pinyin: "xiào", meaning: "trường" },
  { char: "师", pinyin: "shī", meaning: "thầy" },
  { char: "同", pinyin: "tóng", meaning: "cùng" },
  { char: "妈", pinyin: "mā", meaning: "mẹ" },
  { char: "爸", pinyin: "bà", meaning: "bố" },
  { char: "儿", pinyin: "ér", meaning: "con (trai)" },
  { char: "先", pinyin: "xiān", meaning: "trước" },
  { char: "太", pinyin: "tài", meaning: "quá" },
  { char: "漂", pinyin: "piào", meaning: "(xinh) phiêu" },
  { char: "亮", pinyin: "liàng", meaning: "sáng, đẹp" },
  { char: "高", pinyin: "gāo", meaning: "cao" },
  { char: "兴", pinyin: "xìng", meaning: "hứng (vui)" },
  { char: "冷", pinyin: "lěng", meaning: "lạnh" },
  { char: "热", pinyin: "rè", meaning: "nóng" },
  { char: "气", pinyin: "qì", meaning: "khí, thời tiết" },
  { char: "前", pinyin: "qián", meaning: "trước" },
  { char: "后", pinyin: "hòu", meaning: "sau" },
  { char: "里", pinyin: "lǐ", meaning: "trong, dặm" },
  { char: "电", pinyin: "diàn", meaning: "điện" },
  { char: "话", pinyin: "huà", meaning: "lời, nói chuyện" },
  { char: "脑", pinyin: "nǎo", meaning: "não (máy tính)" },
  { char: "影", pinyin: "yǐng", meaning: "bóng, phim" },
  { char: "视", pinyin: "shì", meaning: "nhìn (TV)" },

  // ── HSK2 (trọn bộ chữ đơn thường gặp) ──
  { char: "吧", pinyin: "ba", meaning: "(trợ từ đề nghị)" },
  { char: "吗", pinyin: "ma", meaning: "(trợ từ hỏi)" },
  { char: "呢", pinyin: "ne", meaning: "(trợ từ hỏi)" },
  { char: "让", pinyin: "ràng", meaning: "để, cho phép" },
  { char: "给", pinyin: "gěi", meaning: "cho" },
  { char: "对", pinyin: "duì", meaning: "đúng" },
  { char: "为", pinyin: "wèi", meaning: "vì" },
  { char: "因", pinyin: "yīn", meaning: "vì (nguyên nhân)" },
  { char: "所", pinyin: "suǒ", meaning: "nơi, sở" },
  { char: "以", pinyin: "yǐ", meaning: "lấy, để" },
  { char: "但", pinyin: "dàn", meaning: "nhưng" },
  { char: "还", pinyin: "hái", meaning: "còn, vẫn" },
  { char: "再", pinyin: "zài", meaning: "lại, nữa" },
  { char: "正", pinyin: "zhèng", meaning: "đang, chính" },
  { char: "已", pinyin: "yǐ", meaning: "đã" },
  { char: "经", pinyin: "jīng", meaning: "kinh, đã (qua)" },
  { char: "从", pinyin: "cóng", meaning: "từ" },
  { char: "到", pinyin: "dào", meaning: "đến" },
  { char: "向", pinyin: "xiàng", meaning: "hướng" },
  { char: "离", pinyin: "lí", meaning: "cách, rời" },
  { char: "近", pinyin: "jìn", meaning: "gần" },
  { char: "远", pinyin: "yuǎn", meaning: "xa" },
  { char: "边", pinyin: "biān", meaning: "bên, cạnh" },
  { char: "外", pinyin: "wài", meaning: "ngoài" },
  { char: "内", pinyin: "nèi", meaning: "trong" },
  { char: "左", pinyin: "zuǒ", meaning: "trái" },
  { char: "右", pinyin: "yòu", meaning: "phải" },
  { char: "东", pinyin: "dōng", meaning: "đông" },
  { char: "西", pinyin: "xī", meaning: "tây" },
  { char: "南", pinyin: "nán", meaning: "nam" },
  { char: "路", pinyin: "lù", meaning: "đường" },
  { char: "门", pinyin: "mén", meaning: "cửa" },
  { char: "房", pinyin: "fáng", meaning: "phòng, nhà" },
  { char: "间", pinyin: "jiān", meaning: "gian, giữa" },
  { char: "公", pinyin: "gōng", meaning: "công" },
  { char: "司", pinyin: "sī", meaning: "công ty (司)" },
  { char: "员", pinyin: "yuán", meaning: "nhân viên" },
  { char: "卖", pinyin: "mài", meaning: "bán" },
  { char: "买", pinyin: "mǎi", meaning: "mua" },
  { char: "贵", pinyin: "guì", meaning: "đắt" },
  { char: "便", pinyin: "pián", meaning: "rẻ (tiện)" },
  { char: "宜", pinyin: "yí", meaning: "thích hợp (nghi)" },
  { char: "票", pinyin: "piào", meaning: "vé" },
  { char: "穿", pinyin: "chuān", meaning: "mặc" },
  { char: "衣", pinyin: "yī", meaning: "áo" },
  { char: "服", pinyin: "fú", meaning: "phục, quần áo" },
  { char: "件", pinyin: "jiàn", meaning: "(lượng từ) chiếc" },
  { char: "色", pinyin: "sè", meaning: "màu" },
  { char: "鱼", pinyin: "yú", meaning: "cá" },
  { char: "鸡", pinyin: "jī", meaning: "gà" },
  { char: "蛋", pinyin: "dàn", meaning: "trứng" },
  { char: "羊", pinyin: "yáng", meaning: "dê, cừu" },
  { char: "牛", pinyin: "niú", meaning: "bò" },
  { char: "肉", pinyin: "ròu", meaning: "thịt" },
  { char: "面", pinyin: "miàn", meaning: "mì, mặt" },
  { char: "牛", pinyin: "niú", meaning: "bò" },
  { char: "病", pinyin: "bìng", meaning: "bệnh" },
  { char: "药", pinyin: "yào", meaning: "thuốc" },
  { char: "累", pinyin: "lèi", meaning: "mệt" },
  { char: "忙", pinyin: "máng", meaning: "bận" },
  { char: "快", pinyin: "kuài", meaning: "nhanh" },
  { char: "慢", pinyin: "màn", meaning: "chậm" },
  { char: "早", pinyin: "zǎo", meaning: "sớm" },
  { char: "晚", pinyin: "wǎn", meaning: "muộn, tối" },
  { char: "午", pinyin: "wǔ", meaning: "trưa" },
  { char: "开", pinyin: "kāi", meaning: "mở, bắt đầu" },
  { char: "关", pinyin: "guān", meaning: "đóng, liên quan" },
  { char: "始", pinyin: "shǐ", meaning: "bắt đầu" },
  { char: "完", pinyin: "wán", meaning: "xong" },
  { char: "回", pinyin: "huí", meaning: "về" },
  { char: "进", pinyin: "jìn", meaning: "vào" },
  { char: "送", pinyin: "sòng", meaning: "tặng, đưa" },
  { char: "找", pinyin: "zhǎo", meaning: "tìm" },
  { char: "等", pinyin: "děng", meaning: "đợi" },
  { char: "玩", pinyin: "wán", meaning: "chơi" },
  { char: "跑", pinyin: "pǎo", meaning: "chạy" },
  { char: "唱", pinyin: "chàng", meaning: "hát" },
  { char: "跳", pinyin: "tiào", meaning: "nhảy" },
  { char: "舞", pinyin: "wǔ", meaning: "múa" },
  { char: "踢", pinyin: "tī", meaning: "đá (bóng)" },
  { char: "球", pinyin: "qiú", meaning: "bóng" },
  { char: "游", pinyin: "yóu", meaning: "bơi, du" },
  { char: "泳", pinyin: "yǒng", meaning: "bơi (vịnh)" },
  { char: "懂", pinyin: "dǒng", meaning: "hiểu" },
  { char: "觉", pinyin: "jué", meaning: "cảm thấy, ngủ" },
  { char: "得", pinyin: "de", meaning: "(trợ từ bổ ngữ)" },
  { char: "题", pinyin: "tí", meaning: "đề, câu hỏi" },
  { char: "问", pinyin: "wèn", meaning: "hỏi" },
  { char: "课", pinyin: "kè", meaning: "bài học" },
  { char: "考", pinyin: "kǎo", meaning: "thi" },
  { char: "试", pinyin: "shì", meaning: "thử" },
  { char: "班", pinyin: "bān", meaning: "lớp, ca" },
  { char: "员", pinyin: "yuán", meaning: "nhân viên" },
  { char: "公", pinyin: "gōng", meaning: "công" },
  { char: "意", pinyin: "yì", meaning: "ý" },
  { char: "思", pinyin: "sī", meaning: "nghĩ" },
  { char: "希", pinyin: "xī", meaning: "hi (vọng)" },
  { char: "助", pinyin: "zhù", meaning: "giúp" },
  { char: "帮", pinyin: "bāng", meaning: "giúp đỡ" },
  { char: "重", pinyin: "zhòng", meaning: "nặng, quan trọng" },
  { char: "新", pinyin: "xīn", meaning: "mới" },
  { char: "旧", pinyin: "jiù", meaning: "cũ" },
  { char: "长", pinyin: "cháng", meaning: "dài" },
  { char: "短", pinyin: "duǎn", meaning: "ngắn" },
  { char: "大", pinyin: "dà", meaning: "to" },
  { char: "公", pinyin: "gōng", meaning: "công" },
  { char: "贝", pinyin: "bèi", meaning: "(sò) bối" },
  { char: "记", pinyin: "jì", meaning: "ghi nhớ" },
  { char: "懂", pinyin: "dǒng", meaning: "hiểu" },
];

// Lọc bỏ entry không hợp lệ (không phải đúng 1 chữ Hán) + khử trùng lặp.
export const HANDWRITING_CHARSET: CandidateInfo[] = (() => {
  const seen = new Set<string>();
  const out: CandidateInfo[] = [];
  for (const c of HANDWRITING_CANDIDATES) {
    if (c.char.length !== 1) continue;
    if (!/[㐀-鿿]/.test(c.char)) continue;
    if (seen.has(c.char)) continue;
    seen.add(c.char);
    out.push(c);
  }
  return out;
})();
