/** Kho từ HSK3 (100 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK3: HSKWord[] = [
    { hanzi: "经验", hanViet: "kinh nghiệm", pinyin: "jīng yàn", meaning: "Kinh nghiệm", example: "他有丰富的工作经验。" },
    { hanzi: "感情", hanViet: "cảm tình", pinyin: "gǎn qíng", meaning: "Tình cảm / cảm xúc", example: "他们之间有深厚的感情。" },
    { hanzi: "压力", hanViet: "áp lực", pinyin: "yā lì", meaning: "Áp lực", example: "工作压力很大。" },
    { hanzi: "努力", hanViet: "nỗ lực", pinyin: "nǔ lì", meaning: "Cố gắng / nỗ lực", example: "只要努力，就能成功。" },
    { hanzi: "成功", hanViet: "thành công", pinyin: "chéng gōng", meaning: "Thành công", example: "努力才能成功。" },
    { hanzi: "机会", hanViet: "cơ hội", pinyin: "jī huì", meaning: "Cơ hội", example: "这是一个好机会。" },
    { hanzi: "选择", hanViet: "tuyển trạch", pinyin: "xuǎn zé", meaning: "Lựa chọn", example: "人生有很多选择。" },
    { hanzi: "决定", hanViet: "quyết định", pinyin: "jué dìng", meaning: "Quyết định", example: "你决定了吗？" },
    { hanzi: "改变", hanViet: "cải biến", pinyin: "gǎi biàn", meaning: "Thay đổi", example: "改变需要勇气。" },
    { hanzi: "理解", hanViet: "lý giải", pinyin: "lǐ jiě", meaning: "Hiểu / thông cảm", example: "我理解你的感受。" },
    { hanzi: "关系", hanViet: "quan hệ", pinyin: "guān xì", meaning: "Mối quan hệ", example: "我们的关系很好。" },
    { hanzi: "影响", hanViet: "ảnh hưởng", pinyin: "yǐng xiǎng", meaning: "Ảnh hưởng", example: "音乐影响了我的生活。" },
    { hanzi: "文化", hanViet: "văn hóa", pinyin: "wén huà", meaning: "Văn hóa", example: "中国文化博大精深。" },
    { hanzi: "传统", hanViet: "truyền thống", pinyin: "chuán tǒng", meaning: "Truyền thống", example: "我们要保护传统文化。" },
    { hanzi: "环境", hanViet: "hoàn cảnh", pinyin: "huán jìng", meaning: "Môi trường", example: "保护环境很重要。" },
    { hanzi: "社会", hanViet: "xã hội", pinyin: "shè huì", meaning: "Xã hội", example: "社会在不断进步。" },
    { hanzi: "失败", hanViet: "thất bại", pinyin: "shī bài", meaning: "Thất bại", example: "失败是成功之母。" },
    { hanzi: "表达", hanViet: "biểu đạt", pinyin: "biǎo dá", meaning: "Biểu đạt / thể hiện", example: "我想表达我的感谢。" },
    { hanzi: "发展", hanViet: "phát triển", pinyin: "fā zhǎn", meaning: "Phát triển", example: "城市发展很快。" },
    { hanzi: "现代", hanViet: "hiện đại", pinyin: "xiàn dài", meaning: "Hiện đại", example: "这是一座现代城市。" },
    { hanzi: "习惯", hanViet: "tập quán", pinyin: "xí guàn", meaning: "Thói quen / quen", example: "早起是个好习惯。" },
    { hanzi: "健康", hanViet: "kiện khang", pinyin: "jiàn kāng", meaning: "Sức khỏe / khỏe mạnh", example: "祝你身体健康。" },
    { hanzi: "节日", hanViet: "tiết nhật", pinyin: "jié rì", meaning: "Ngày lễ", example: "春节是最重要的节日。" },
    { hanzi: "礼物", hanViet: "lễ vật", pinyin: "lǐ wù", meaning: "Món quà", example: "这是给你的礼物。" },
    { hanzi: "安静", hanViet: "an tĩnh", pinyin: "ān jìng", meaning: "Yên tĩnh", example: "图书馆里很安静。" },
    { hanzi: "害怕", hanViet: "hại phạ", pinyin: "hài pà", meaning: "Sợ hãi", example: "别害怕，有我在。" },
    { hanzi: "难过", hanViet: "nan quá", pinyin: "nán guò", meaning: "Buồn / khó chịu", example: "听到这个消息我很难过。" },
    { hanzi: "记得", hanViet: "ký đắc", pinyin: "jì de", meaning: "Nhớ / còn nhớ", example: "你还记得我吗？" },
    { hanzi: "相信", hanViet: "tương tín", pinyin: "xiāng xìn", meaning: "Tin tưởng", example: "我相信你能做到。" },
    { hanzi: "梦想", hanViet: "mộng tưởng", pinyin: "mèng xiǎng", meaning: "Ước mơ", example: "每个人都有自己的梦想。" },
  { hanzi: "打算", hanViet: "đả toán", pinyin: "dǎ suàn", meaning: "Dự định", example: "你周末打算做什么？" },
  { hanzi: "需要", hanViet: "nhu yếu", pinyin: "xū yào", meaning: "Cần", example: "你需要帮忙吗？" },
  { hanzi: "应该", hanViet: "ưng cai", pinyin: "yīng gāi", meaning: "Nên / phải", example: "你应该早点儿睡觉。" },
  { hanzi: "必须", hanViet: "tất tu", pinyin: "bì xū", meaning: "Bắt buộc phải", example: "明天必须交作业。" },
  { hanzi: "同意", hanViet: "đồng ý", pinyin: "tóng yì", meaning: "Đồng ý", example: "我同意你的看法。" },
  { hanzi: "反对", hanViet: "phản đối", pinyin: "fǎn duì", meaning: "Phản đối", example: "没有人反对这个决定。" },
  { hanzi: "担心", hanViet: "đam tâm", pinyin: "dān xīn", meaning: "Lo lắng", example: "妈妈很担心你的身体。" },
  { hanzi: "放心", hanViet: "phóng tâm", pinyin: "fàng xīn", meaning: "Yên tâm", example: "放心吧，一切都会好的。" },
  { hanzi: "注意", hanViet: "chú ý", pinyin: "zhù yì", meaning: "Chú ý", example: "过马路要注意安全。" },
  { hanzi: "发现", hanViet: "phát hiện", pinyin: "fā xiàn", meaning: "Phát hiện", example: "我发现他最近很努力。" },
  { hanzi: "解释", hanViet: "giải thích", pinyin: "jiě shì", meaning: "Giải thích", example: "请你解释一下这个词。" },
  { hanzi: "比较", hanViet: "tỷ giáo", pinyin: "bǐ jiào", meaning: "Tương đối / so sánh", example: "这本书比较难。" },
  { hanzi: "特别", hanViet: "đặc biệt", pinyin: "tè bié", meaning: "Đặc biệt / vô cùng", example: "今天的菜特别好吃。" },
  { hanzi: "突然", hanViet: "đột nhiên", pinyin: "tū rán", meaning: "Đột nhiên", example: "天突然下起了大雨。" },
  { hanzi: "终于", hanViet: "chung vu", pinyin: "zhōng yú", meaning: "Cuối cùng cũng", example: "我终于学会了这首歌。" },
  { hanzi: "经常", hanViet: "kinh thường", pinyin: "jīng cháng", meaning: "Thường xuyên", example: "他经常去图书馆。" },
  { hanzi: "马上", hanViet: "mã thượng", pinyin: "mǎ shàng", meaning: "Ngay lập tức", example: "等一下，我马上来。" },
  { hanzi: "刚才", hanViet: "cương tài", pinyin: "gāng cái", meaning: "Vừa nãy", example: "刚才谁给我打电话？" },
  { hanzi: "以前", hanViet: "dĩ tiền", pinyin: "yǐ qián", meaning: "Trước đây", example: "以前我不会说汉语。" },
  { hanzi: "以后", hanViet: "dĩ hậu", pinyin: "yǐ hòu", meaning: "Sau này", example: "以后我想去中国留学。" },
  { hanzi: "世界", hanViet: "thế giới", pinyin: "shì jiè", meaning: "Thế giới", example: "我想看看这个世界。" },
  { hanzi: "国家", hanViet: "quốc gia", pinyin: "guó jiā", meaning: "Quốc gia / đất nước", example: "你去过哪些国家？" },
  { hanzi: "城市", hanViet: "thành thị", pinyin: "chéng shì", meaning: "Thành phố", example: "这座城市很漂亮。" },
  { hanzi: "季节", hanViet: "quý tiết", pinyin: "jì jié", meaning: "Mùa", example: "你最喜欢哪个季节？" },
  { hanzi: "春天", hanViet: "xuân thiên", pinyin: "chūn tiān", meaning: "Mùa xuân", example: "春天来了，花开了。" },
  { hanzi: "夏天", hanViet: "hạ thiên", pinyin: "xià tiān", meaning: "Mùa hè", example: "夏天我常去游泳。" },
  { hanzi: "秋天", hanViet: "thu thiên", pinyin: "qiū tiān", meaning: "Mùa thu", example: "秋天的天气很舒服。" },
  { hanzi: "冬天", hanViet: "đông thiên", pinyin: "dōng tiān", meaning: "Mùa đông", example: "北京的冬天很冷。" },
  { hanzi: "周末", hanViet: "chu mạt", pinyin: "zhōu mò", meaning: "Cuối tuần", example: "周末你有什么打算？" },
  { hanzi: "办法", hanViet: "biện pháp", pinyin: "bàn fǎ", meaning: "Cách / biện pháp", example: "别着急，一定有办法。" },
  { hanzi: "参加", hanViet: "tham gia", pinyin: "cān jiā", meaning: "Tham gia", example: "我想参加这个活动。" },
  { hanzi: "结束", hanViet: "kết thúc", pinyin: "jié shù", meaning: "Kết thúc", example: "会议十点结束。" },
  { hanzi: "离开", hanViet: "ly khai", pinyin: "lí kāi", meaning: "Rời khỏi", example: "他昨天离开了北京。" },
  { hanzi: "借", hanViet: "tá", pinyin: "jiè", meaning: "Mượn / cho mượn", example: "我想借这本书。" },
  { hanzi: "换", hanViet: "hoán", pinyin: "huàn", meaning: "Đổi", example: "我想换一件大一点儿的。" },
  { hanzi: "检查", hanViet: "kiểm tra", pinyin: "jiǎn chá", meaning: "Kiểm tra", example: "医生给他检查了身体。" },
  { hanzi: "练习", hanViet: "luyện tập", pinyin: "liàn xí", meaning: "Luyện tập", example: "我每天练习写汉字。" },
  { hanzi: "迟到", hanViet: "trì đáo", pinyin: "chí dào", meaning: "Đến muộn", example: "对不起，我迟到了。" },
  { hanzi: "搬", hanViet: "ban", pinyin: "bān", meaning: "Chuyển / dọn (nhà, đồ)", example: "我们下个月搬家。" },
  { hanzi: "带", hanViet: "đới", pinyin: "dài", meaning: "Mang theo / dẫn", example: "别忘了带伞。" },
  { hanzi: "拿", hanViet: "nã", pinyin: "ná", meaning: "Cầm / lấy", example: "请帮我拿一下杯子。" },
  { hanzi: "放", hanViet: "phóng", pinyin: "fàng", meaning: "Đặt / để / thả", example: "把书放在桌子上吧。" },
  { hanzi: "接", hanViet: "tiếp", pinyin: "jiē", meaning: "Đón / nhận", example: "爸爸去机场接妈妈。" },
  { hanzi: "教", hanViet: "giáo", pinyin: "jiāo", meaning: "Dạy", example: "她教我们汉语。" },
  { hanzi: "故事", hanViet: "cố sự", pinyin: "gù shi", meaning: "Câu chuyện", example: "奶奶给我讲了一个故事。" },
  { hanzi: "历史", hanViet: "lịch sử", pinyin: "lì shǐ", meaning: "Lịch sử", example: "中国有很长的历史。" },
  { hanzi: "音乐", hanViet: "âm nhạc", pinyin: "yīn yuè", meaning: "Âm nhạc", example: "我喜欢听音乐。" },
  { hanzi: "体育", hanViet: "thể dục", pinyin: "tǐ yù", meaning: "Thể dục / thể thao", example: "他体育很好。" },
  { hanzi: "地图", hanViet: "địa đồ", pinyin: "dì tú", meaning: "Bản đồ", example: "看地图就不会迷路了。" },
  { hanzi: "邻居", hanViet: "lân cư", pinyin: "lín jū", meaning: "Hàng xóm", example: "我们的邻居很友好。" },
  { hanzi: "同事", hanViet: "đồng sự", pinyin: "tóng shì", meaning: "Đồng nghiệp", example: "我和同事一起吃午饭。" },
  { hanzi: "阿姨", hanViet: "a di", pinyin: "ā yí", meaning: "Cô / dì", example: "阿姨做的菜很好吃。" },
  { hanzi: "叔叔", hanViet: "thúc thúc", pinyin: "shū shu", meaning: "Chú", example: "叔叔送我一个礼物。" },
  { hanzi: "熊猫", hanViet: "hùng miêu", pinyin: "xióng māo", meaning: "Gấu trúc", example: "熊猫真可爱！" },
  { hanzi: "香蕉", hanViet: "hương tiêu", pinyin: "xiāng jiāo", meaning: "Chuối", example: "我每天吃一根香蕉。" },
  { hanzi: "葡萄", hanViet: "bồ đào", pinyin: "pú tao", meaning: "Nho", example: "这些葡萄很甜。" },
  { hanzi: "蛋糕", hanViet: "đản cao", pinyin: "dàn gāo", meaning: "Bánh kem / bánh ngọt", example: "生日要吃蛋糕。" },
  { hanzi: "银行", hanViet: "ngân hàng", pinyin: "yín háng", meaning: "Ngân hàng", example: "银行九点开门。" },
  { hanzi: "超市", hanViet: "siêu thị", pinyin: "chāo shì", meaning: "Siêu thị", example: "妈妈去超市买东西了。" },
  { hanzi: "公园", hanViet: "công viên", pinyin: "gōng yuán", meaning: "Công viên", example: "公园里有很多人散步。" },
  { hanzi: "图书馆", hanViet: "đồ thư quán", pinyin: "tú shū guǎn", meaning: "Thư viện", example: "我在图书馆看书。" },
  { hanzi: "厨房", hanViet: "trù phòng", pinyin: "chú fáng", meaning: "Nhà bếp", example: "妈妈在厨房做饭。" },
  { hanzi: "洗手间", hanViet: "tẩy thủ gian", pinyin: "xǐ shǒu jiān", meaning: "Nhà vệ sinh", example: "请问洗手间在哪儿？" },
  { hanzi: "电梯", hanViet: "điện thê", pinyin: "diàn tī", meaning: "Thang máy", example: "我们坐电梯上楼吧。" },
  { hanzi: "钱包", hanViet: "tiền bao", pinyin: "qián bāo", meaning: "Ví tiền", example: "我的钱包不见了！" },
  { hanzi: "眼镜", hanViet: "nhãn kính", pinyin: "yǎn jìng", meaning: "Kính mắt", example: "他戴着一副眼镜。" },
  { hanzi: "衬衫", hanViet: "sấn sam", pinyin: "chèn shān", meaning: "Áo sơ mi", example: "这件衬衫很好看。" },
  { hanzi: "裤子", hanViet: "khố tử", pinyin: "kù zi", meaning: "Quần", example: "我想买一条新裤子。" },
  { hanzi: "鞋", hanViet: "hài", pinyin: "xié", meaning: "Giày", example: "这双鞋有点儿小。" },
  { hanzi: "帽子", hanViet: "mạo tử", pinyin: "mào zi", meaning: "Mũ", example: "冬天要戴帽子。" },
];
