/** Kho từ HSK2 (150 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK2: HSKWord[] = [
    { hanzi: "觉得", hanViet: "giác đắc", pinyin: "jué de", meaning: "Cảm thấy / nghĩ rằng", example: "我觉得今天很开心。" },
    { hanzi: "知道", hanViet: "tri đạo", pinyin: "zhī dào", meaning: "Biết", example: "你知道他在哪里吗？" },
    { hanzi: "希望", hanViet: "hy vọng", pinyin: "xī wàng", meaning: "Hy vọng", example: "我希望你成功。" },
    { hanzi: "开心", hanViet: "khai tâm", pinyin: "kāi xīn", meaning: "Vui vẻ / hạnh phúc", example: "今天我很开心。" },
    { hanzi: "漂亮", hanViet: "phiêu lượng", pinyin: "piào liang", meaning: "Đẹp", example: "这件衣服很漂亮。" },
    { hanzi: "帮助", hanViet: "bang trợ", pinyin: "bāng zhù", meaning: "Giúp đỡ", example: "谢谢你的帮助。" },
    { hanzi: "问题", hanViet: "vấn đề", pinyin: "wèn tí", meaning: "Vấn đề / câu hỏi", example: "我有一个问题。" },
    { hanzi: "时间", hanViet: "thời gian", pinyin: "shí jiān", meaning: "Thời gian", example: "我没有时间。" },
    { hanzi: "天气", hanViet: "thiên khí", pinyin: "tiān qì", meaning: "Thời tiết", example: "今天天气很好。" },
    { hanzi: "生活", hanViet: "sinh hoạt", pinyin: "shēng huó", meaning: "Cuộc sống", example: "我的生活很充实。" },
    { hanzi: "工作", hanViet: "công tác", pinyin: "gōng zuò", meaning: "Công việc / làm việc", example: "他工作很努力。" },
    { hanzi: "学习", hanViet: "học tập", pinyin: "xué xí", meaning: "Học tập", example: "我喜欢学习汉语。" },
    { hanzi: "快乐", hanViet: "khoái lạc", pinyin: "kuài lè", meaning: "Vui vẻ / hạnh phúc", example: "祝你快乐！" },
    { hanzi: "重要", hanViet: "trọng yếu", pinyin: "zhòng yào", meaning: "Quan trọng", example: "这件事很重要。" },
    { hanzi: "因为", hanViet: "nhân vị", pinyin: "yīn wèi", meaning: "Bởi vì", example: "因为下雨，我没出门。" },
    { hanzi: "所以", hanViet: "sở dĩ", pinyin: "suǒ yǐ", meaning: "Vì vậy / cho nên", example: "他努力，所以成功了。" },
    { hanzi: "但是", hanViet: "đãn thị", pinyin: "dàn shì", meaning: "Nhưng / tuy nhiên", example: "我想去，但是没时间。" },
    { hanzi: "身体", hanViet: "thân thể", pinyin: "shēn tǐ", meaning: "Cơ thể / sức khỏe", example: "注意身体健康。" },
    { hanzi: "地方", hanViet: "địa phương", pinyin: "dì fāng", meaning: "Nơi / địa điểm", example: "这是一个好地方。" },
    { hanzi: "事情", hanViet: "sự tình", pinyin: "shì qíng", meaning: "Sự việc / chuyện", example: "有什么事情吗？" },
    { hanzi: "运动", hanViet: "vận động", pinyin: "yùn dòng", meaning: "Thể thao / vận động", example: "我每天运动一小时。" },
    { hanzi: "颜色", hanViet: "nhan sắc", pinyin: "yán sè", meaning: "Màu sắc", example: "你喜欢什么颜色？" },
    { hanzi: "旅游", hanViet: "lữ du", pinyin: "lǚ yóu", meaning: "Du lịch", example: "我想去中国旅游。" },
    { hanzi: "准备", hanViet: "chuẩn bị", pinyin: "zhǔn bèi", meaning: "Chuẩn bị", example: "我在准备考试。" },
    { hanzi: "介绍", hanViet: "giới thiệu", pinyin: "jiè shào", meaning: "Giới thiệu", example: "我来介绍一下自己。" },
    { hanzi: "休息", hanViet: "hưu tức", pinyin: "xiū xi", meaning: "Nghỉ ngơi", example: "累了就休息一下。" },
    { hanzi: "唱歌", hanViet: "xướng ca", pinyin: "chàng gē", meaning: "Hát", example: "她唱歌很好听。" },
    { hanzi: "跳舞", hanViet: "khiêu vũ", pinyin: "tiào wǔ", meaning: "Nhảy múa", example: "我们一起跳舞吧。" },
    { hanzi: "医院", hanViet: "y viện", pinyin: "yī yuàn", meaning: "Bệnh viện", example: "他在医院工作。" },
    { hanzi: "考试", hanViet: "khảo thí", pinyin: "kǎo shì", meaning: "Thi / kỳ thi", example: "明天有考试。" },
    { hanzi: "起床", hanViet: "khởi sàng", pinyin: "qǐ chuáng", meaning: "Thức dậy", example: "我每天六点起床。" },
    { hanzi: "睡觉", hanViet: "thụy giác", pinyin: "shuì jiào", meaning: "Ngủ", example: "我十一点睡觉。" },
    { hanzi: "已经", hanViet: "dĩ kinh", pinyin: "yǐ jīng", meaning: "Đã / rồi", example: "我已经吃饭了。" },
    { hanzi: "真", hanViet: "chân", pinyin: "zhēn", meaning: "Thật / thật sự", example: "这里真漂亮！" },
    { hanzi: "非常", hanViet: "phi thường", pinyin: "fēi cháng", meaning: "Vô cùng / rất", example: "我非常喜欢这首歌。" },
    { hanzi: "可能", hanViet: "khả năng", pinyin: "kě néng", meaning: "Có thể / có lẽ", example: "明天可能下雨。" },
    { hanzi: "开始", hanViet: "khai thủy", pinyin: "kāi shǐ", meaning: "Bắt đầu", example: "电影开始了。" },
    { hanzi: "等", hanViet: "đẳng", pinyin: "děng", meaning: "Chờ / đợi", example: "请等我一下。" },
    { hanzi: "找", hanViet: "trảo", pinyin: "zhǎo", meaning: "Tìm", example: "你在找什么？" },
    { hanzi: "给", hanViet: "cấp", pinyin: "gěi", meaning: "Cho / đưa", example: "把书给我。" },
    { hanzi: "告诉", hanViet: "cáo tố", pinyin: "gào su", meaning: "Nói cho biết", example: "告诉我你的名字。" },
    { hanzi: "早上", hanViet: "tảo thượng", pinyin: "zǎo shang", meaning: "Buổi sáng", example: "早上好！" },
    { hanzi: "晚上", hanViet: "vãn thượng", pinyin: "wǎn shang", meaning: "Buổi tối", example: "晚上我们一起吃饭。" },
    { hanzi: "每天", hanViet: "mỗi thiên", pinyin: "měi tiān", meaning: "Mỗi ngày", example: "我每天都学汉语。" },
    { hanzi: "哥哥", hanViet: "ca ca", pinyin: "gē ge", meaning: "Anh trai", example: "我哥哥很高。" },
    { hanzi: "妹妹", hanViet: "muội muội", pinyin: "mèi mei", meaning: "Em gái", example: "我妹妹喜欢唱歌。" },
    { hanzi: "咖啡", hanViet: "ca phê", pinyin: "kā fēi", meaning: "Cà phê", example: "我想喝咖啡。" },
    { hanzi: "牛奶", hanViet: "ngưu nãi", pinyin: "niú nǎi", meaning: "Sữa bò", example: "早上我喝牛奶。" },
    { hanzi: "手机", hanViet: "thủ cơ", pinyin: "shǒu jī", meaning: "Điện thoại di động", example: "我的手机没电了。" },
    { hanzi: "房间", hanViet: "phòng gian", pinyin: "fáng jiān", meaning: "Căn phòng", example: "我的房间很干净。" },
    { hanzi: "累", hanViet: "luy", pinyin: "lèi", meaning: "Mệt", example: "我今天很累。" },
    { hanzi: "忙", hanViet: "mang", pinyin: "máng", meaning: "Bận", example: "你最近忙吗？" },
    { hanzi: "高", hanViet: "cao", pinyin: "gāo", meaning: "Cao", example: "他个子很高。" },
    { hanzi: "新", hanViet: "tân", pinyin: "xīn", meaning: "Mới", example: "这是我的新手机。" },
    { hanzi: "旧", hanViet: "cựu", pinyin: "jiù", meaning: "Cũ", example: "这本书很旧了。" },
    { hanzi: "长", hanViet: "trường", pinyin: "cháng", meaning: "Dài", example: "这条路很长。" },
    { hanzi: "白", hanViet: "bạch", pinyin: "bái", meaning: "Trắng", example: "她穿白衣服很好看。" },
    { hanzi: "黑", hanViet: "hắc", pinyin: "hēi", meaning: "Đen / tối", example: "天黑了，回家吧。" },
    { hanzi: "红", hanViet: "hồng", pinyin: "hóng", meaning: "Đỏ", example: "我喜欢红色的花。" },
    { hanzi: "贵", hanViet: "quý", pinyin: "guì", meaning: "Đắt", example: "这个太贵了。" },
    { hanzi: "便宜", hanViet: "tiện nghi", pinyin: "pián yi", meaning: "Rẻ", example: "这家店的东西很便宜。" },
    { hanzi: "近", hanViet: "cận", pinyin: "jìn", meaning: "Gần", example: "我家离学校很近。" },
    { hanzi: "远", hanViet: "viễn", pinyin: "yuǎn", meaning: "Xa", example: "火车站离这儿远吗？" },
    { hanzi: "快", hanViet: "khoái", pinyin: "kuài", meaning: "Nhanh", example: "时间过得真快。" },
    { hanzi: "慢", hanViet: "mạn", pinyin: "màn", meaning: "Chậm", example: "请说慢一点儿。" },
    { hanzi: "好吃", hanViet: "hảo cật", pinyin: "hǎo chī", meaning: "Ngon", example: "妈妈做的菜真好吃。" },
    { hanzi: "对", hanViet: "đối", pinyin: "duì", meaning: "Đúng / đối với", example: "你说得对。" },
    { hanzi: "错", hanViet: "thác", pinyin: "cuò", meaning: "Sai", example: "对不起，我错了。" },
    { hanzi: "懂", hanViet: "đổng", pinyin: "dǒng", meaning: "Hiểu", example: "你懂我的意思吗？" },
    { hanzi: "玩", hanViet: "ngoạn", pinyin: "wán", meaning: "Chơi", example: "周末我们去公园玩吧。" },
    { hanzi: "笑", hanViet: "tiếu", pinyin: "xiào", meaning: "Cười", example: "她笑得很开心。" },
    { hanzi: "哭", hanViet: "khốc", pinyin: "kū", meaning: "Khóc", example: "孩子哭了，快去看看。" },
    { hanzi: "走", hanViet: "tẩu", pinyin: "zǒu", meaning: "Đi bộ / rời đi", example: "我们走吧。" },
    { hanzi: "跑步", hanViet: "bào bộ", pinyin: "pǎo bù", meaning: "Chạy bộ", example: "我每天早上跑步。" },
    { hanzi: "游泳", hanViet: "du vịnh", pinyin: "yóu yǒng", meaning: "Bơi", example: "夏天我喜欢游泳。" },
    { hanzi: "穿", hanViet: "xuyên", pinyin: "chuān", meaning: "Mặc (quần áo)", example: "今天冷，多穿一点儿。" },
    { hanzi: "洗", hanViet: "tẩy", pinyin: "xǐ", meaning: "Rửa / giặt", example: "吃饭前要洗手。" },
    { hanzi: "卖", hanViet: "mại", pinyin: "mài", meaning: "Bán", example: "这家店卖水果。" },
    { hanzi: "送", hanViet: "tống", pinyin: "sòng", meaning: "Tặng / đưa tiễn", example: "他送我一本书。" },
    { hanzi: "还", hanViet: "hoàn", pinyin: "hái / huán", meaning: "Vẫn còn / trả lại", example: "我还想再看一次。" },
    { hanzi: "进", hanViet: "tiến", pinyin: "jìn", meaning: "Vào", example: "请进！" },
    { hanzi: "出", hanViet: "xuất", pinyin: "chū", meaning: "Ra", example: "他出门了。" },
    { hanzi: "到", hanViet: "đáo", pinyin: "dào", meaning: "Đến / tới nơi", example: "我到家了。" },
    { hanzi: "让", hanViet: "nhượng", pinyin: "ràng", meaning: "Để cho / nhường", example: "妈妈不让我玩手机。" },
    { hanzi: "问", hanViet: "vấn", pinyin: "wèn", meaning: "Hỏi", example: "我想问一个问题。" },
    { hanzi: "回答", hanViet: "hồi đáp", pinyin: "huí dá", meaning: "Trả lời", example: "请回答我的问题。" },
    { hanzi: "姐姐", hanViet: "tỷ tỷ", pinyin: "jiě jie", meaning: "Chị gái", example: "我姐姐在北京工作。" },
    { hanzi: "弟弟", hanViet: "đệ đệ", pinyin: "dì di", meaning: "Em trai", example: "我弟弟今年十岁。" },
    { hanzi: "孩子", hanViet: "hài tử", pinyin: "hái zi", meaning: "Đứa trẻ / con", example: "这个孩子很聪明。" },
    { hanzi: "丈夫", hanViet: "trượng phu", pinyin: "zhàng fu", meaning: "Chồng", example: "她丈夫是医生。" },
    { hanzi: "妻子", hanViet: "thê tử", pinyin: "qī zi", meaning: "Vợ", example: "他和妻子一起去旅游。" },
    { hanzi: "服务员", hanViet: "phục vụ viên", pinyin: "fú wù yuán", meaning: "Nhân viên phục vụ", example: "服务员，买单！" },
    { hanzi: "鸡蛋", hanViet: "kê đản", pinyin: "jī dàn", meaning: "Trứng gà", example: "我早上吃了两个鸡蛋。" },
    { hanzi: "面条", hanViet: "miến điều", pinyin: "miàn tiáo", meaning: "Mì sợi", example: "中午我们吃面条吧。" },
    { hanzi: "西瓜", hanViet: "tây qua", pinyin: "xī guā", meaning: "Dưa hấu", example: "夏天吃西瓜最舒服。" },
    { hanzi: "票", hanViet: "phiếu", pinyin: "piào", meaning: "Vé", example: "我买了两张电影票。" },
    { hanzi: "路", hanViet: "lộ", pinyin: "lù", meaning: "Đường", example: "这条路我走过很多次。" },
    { hanzi: "门", hanViet: "môn", pinyin: "mén", meaning: "Cửa", example: "请关门。" },
    { hanzi: "教室", hanViet: "giáo thất", pinyin: "jiào shì", meaning: "Phòng học", example: "教室里有很多学生。" },
    { hanzi: "公司", hanViet: "công ty", pinyin: "gōng sī", meaning: "Công ty", example: "他在一家大公司工作。" },
  { hanzi: "洗澡", hanViet: "tẩy táo", pinyin: "xǐ zǎo", meaning: "Tắm", example: "我每天晚上洗澡。" },
  { hanzi: "上班", hanViet: "thượng ban", pinyin: "shàng bān", meaning: "Đi làm", example: "爸爸八点去上班。" },
  { hanzi: "下班", hanViet: "hạ ban", pinyin: "xià bān", meaning: "Tan làm", example: "你几点下班？" },
  { hanzi: "上课", hanViet: "thượng khóa", pinyin: "shàng kè", meaning: "Vào học / lên lớp", example: "我们九点上课。" },
  { hanzi: "下课", hanViet: "hạ khóa", pinyin: "xià kè", meaning: "Tan học", example: "下课后一起去吃饭吧。" },
  { hanzi: "见面", hanViet: "kiến diện", pinyin: "jiàn miàn", meaning: "Gặp mặt", example: "我们明天见面吧。" },
  { hanzi: "聊天", hanViet: "liêu thiên", pinyin: "liáo tiān", meaning: "Trò chuyện / tán gẫu", example: "我喜欢和朋友聊天。" },
  { hanzi: "打球", hanViet: "đả cầu", pinyin: "dǎ qiú", meaning: "Chơi bóng", example: "周末我们去打球。" },
  { hanzi: "爬山", hanViet: "bà sơn", pinyin: "pá shān", meaning: "Leo núi", example: "秋天爬山很舒服。" },
  { hanzi: "散步", hanViet: "tán bộ", pinyin: "sàn bù", meaning: "Đi dạo", example: "晚饭后我们去散步。" },
  { hanzi: "生病", hanViet: "sinh bệnh", pinyin: "shēng bìng", meaning: "Bị ốm", example: "他生病了，今天不来上课。" },
  { hanzi: "吃药", hanViet: "cật dược", pinyin: "chī yào", meaning: "Uống thuốc", example: "记得按时吃药。" },
  { hanzi: "发烧", hanViet: "phát thiêu", pinyin: "fā shāo", meaning: "Sốt", example: "孩子发烧了，快去医院。" },
  { hanzi: "感冒", hanViet: "cảm mạo", pinyin: "gǎn mào", meaning: "Cảm cúm", example: "天冷了，小心感冒。" },
  { hanzi: "疼", hanViet: "đằng", pinyin: "téng", meaning: "Đau", example: "我头疼，想休息一下。" },
  { hanzi: "舒服", hanViet: "thư phục", pinyin: "shū fu", meaning: "Dễ chịu / thoải mái", example: "今天天气很舒服。" },
  { hanzi: "干净", hanViet: "can tịnh", pinyin: "gān jìng", meaning: "Sạch sẽ", example: "他的房间很干净。" },
  { hanzi: "聪明", hanViet: "thông minh", pinyin: "cōng ming", meaning: "Thông minh", example: "这个孩子很聪明。" },
  { hanzi: "可爱", hanViet: "khả ái", pinyin: "kě ài", meaning: "Đáng yêu", example: "这只小猫真可爱。" },
  { hanzi: "有名", hanViet: "hữu danh", pinyin: "yǒu míng", meaning: "Nổi tiếng", example: "这家饭店很有名。" },
  { hanzi: "一样", hanViet: "nhất dạng", pinyin: "yí yàng", meaning: "Giống nhau", example: "我们的手机一样。" },
  { hanzi: "一起", hanViet: "nhất khởi", pinyin: "yì qǐ", meaning: "Cùng nhau", example: "我们一起学汉语吧。" },
  { hanzi: "一边", hanViet: "nhất biên", pinyin: "yì biān", meaning: "Vừa... vừa...", example: "他一边走一边唱歌。" },
  { hanzi: "有点儿", hanViet: "hữu điểm nhi", pinyin: "yǒu diǎnr", meaning: "Hơi / có chút", example: "今天有点儿冷。" },
  { hanzi: "最", hanViet: "tối", pinyin: "zuì", meaning: "Nhất (so sánh nhất)", example: "我最喜欢春天。" },
  { hanzi: "更", hanViet: "cánh", pinyin: "gèng", meaning: "Càng / hơn nữa", example: "今天比昨天更热。" },
  { hanzi: "别", hanViet: "biệt", pinyin: "bié", meaning: "Đừng", example: "别担心，有我在。" },
  { hanzi: "再", hanViet: "tái", pinyin: "zài", meaning: "Lại / thêm lần nữa", example: "请再说一遍。" },
  { hanzi: "又", hanViet: "hựu", pinyin: "yòu", meaning: "Lại (đã xảy ra)", example: "他又迟到了。" },
  { hanzi: "就", hanViet: "tựu", pinyin: "jiù", meaning: "Thì / liền / ngay", example: "我马上就来。" },
  { hanzi: "才", hanViet: "tài", pinyin: "cái", meaning: "Mới (muộn hơn dự kiến)", example: "他十二点才睡觉。" },
  { hanzi: "还是", hanViet: "hoàn thị", pinyin: "hái shi", meaning: "Hay là / vẫn nên", example: "你喝茶还是咖啡？" },
  { hanzi: "或者", hanViet: "hoặc giả", pinyin: "huò zhě", meaning: "Hoặc (trong câu kể)", example: "周末我看书或者运动。" },
  { hanzi: "虽然", hanViet: "tuy nhiên", pinyin: "suī rán", meaning: "Tuy rằng", example: "虽然很累，但是我很开心。" },
  { hanzi: "如果", hanViet: "như quả", pinyin: "rú guǒ", meaning: "Nếu như", example: "如果明天下雨，我们就不去了。" },
  { hanzi: "跟", hanViet: "cân", pinyin: "gēn", meaning: "Với / cùng", example: "我跟你一起去。" },
  { hanzi: "离", hanViet: "ly", pinyin: "lí", meaning: "Cách (khoảng cách)", example: "我家离公司不远。" },
  { hanzi: "从", hanViet: "tòng", pinyin: "cóng", meaning: "Từ (xuất phát)", example: "我从越南来。" },
  { hanzi: "向", hanViet: "hướng", pinyin: "xiàng", meaning: "Về phía / hướng tới", example: "向前走，然后右转。" },
  { hanzi: "往", hanViet: "vãng", pinyin: "wǎng", meaning: "Về phía (di chuyển)", example: "往前走十分钟就到了。" },
  { hanzi: "比", hanViet: "tỷ", pinyin: "bǐ", meaning: "So với / hơn", example: "他比我高。" },
  { hanzi: "把", hanViet: "bả", pinyin: "bǎ", meaning: "Đem / lấy (cấu trúc 把)", example: "请把门关上。" },
  { hanzi: "被", hanViet: "bị", pinyin: "bèi", meaning: "Bị / được (bị động)", example: "我的咖啡被他喝了。" },
  { hanzi: "着", hanViet: "trước", pinyin: "zhe", meaning: "Đang (trạng thái kéo dài)", example: "门开着呢。" },
  { hanzi: "过", hanViet: "quá", pinyin: "guò", meaning: "Đã từng", example: "我去过北京。" },
  { hanzi: "完", hanViet: "hoàn", pinyin: "wán", meaning: "Xong / hết", example: "作业做完了。" },
  { hanzi: "次", hanViet: "thứ", pinyin: "cì", meaning: "Lần (lượng từ)", example: "我去过两次中国。" },
  { hanzi: "件", hanViet: "kiện", pinyin: "jiàn", meaning: "Chiếc / việc (lượng từ)", example: "我买了一件衣服。" },
  { hanzi: "张", hanViet: "trương", pinyin: "zhāng", meaning: "Tờ / tấm (lượng từ)", example: "桌上有一张纸。" },
  { hanzi: "条", hanViet: "điều", pinyin: "tiáo", meaning: "Con / chiếc (vật dài)", example: "这条路很安静。" },
];
