/** Kho từ HSK6 (60 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK6: HSKWord[] = [
    { hanzi: "意境", hanViet: "ý cảnh", pinyin: "yì jìng", meaning: "Ý cảnh / thi cảnh", example: "这首诗意境深远。" },
    { hanzi: "韵味", hanViet: "vận vị", pinyin: "yùn wèi", meaning: "Vẻ đẹp tinh tế / hương vị", example: "这首曲子很有韵味。" },
    { hanzi: "沉淀", hanViet: "trầm điến", pinyin: "chén diàn", meaning: "Lắng đọng / tích lũy", example: "时间让情感沉淀。" },
    { hanzi: "渗透", hanViet: "thẩm thấu", pinyin: "shèn tòu", meaning: "Thấm sâu / xâm nhập", example: "文化渗透到生活各处。" },
    { hanzi: "蕴含", hanViet: "uẩn hàm", pinyin: "yùn hán", meaning: "Chứa đựng / ẩn chứa", example: "这首诗蕴含深意。" },
    { hanzi: "折射", hanViet: "chiết xạ", pinyin: "zhé shè", meaning: "Phản chiếu / khúc xạ", example: "语言折射出文化特征。" },
    { hanzi: "凝聚", hanViet: "ngưng tụ", pinyin: "níng jù", meaning: "Kết tụ / đoàn kết", example: "音乐凝聚了人心。" },
    { hanzi: "交融", hanViet: "giao dung", pinyin: "jiāo róng", meaning: "Giao thoa / hòa quyện", example: "中西文化相互交融。" },
    { hanzi: "绽放", hanViet: "trán phóng", pinyin: "zhàn fàng", meaning: "Nở rộ / tỏa sáng", example: "青春如花朵绽放。" },
    { hanzi: "流逝", hanViet: "lưu thệ", pinyin: "liú shì", meaning: "Trôi qua / tàn phai", example: "岁月流逝，青春不再。" },
    { hanzi: "领悟", hanViet: "lĩnh ngộ", pinyin: "lǐng wù", meaning: "Lĩnh hội / giác ngộ", example: "经历后才能领悟真谛。" },
    { hanzi: "追溯", hanViet: "truy tố", pinyin: "zhuī sù", meaning: "Truy nguyên / nhìn lại", example: "追溯历史的根源。" },
    { hanzi: "传承", hanViet: "truyền thừa", pinyin: "chuán chéng", meaning: "Truyền thừa / kế thừa", example: "传承文化是我们的责任。" },
    { hanzi: "铭记", hanViet: "minh ký", pinyin: "míng jì", meaning: "Khắc ghi / ghi nhớ", example: "我们要铭记历史教训。" },
    { hanzi: "蜕变", hanViet: "thuế biến", pinyin: "tuì biàn", meaning: "Biến đổi / lột xác", example: "他经历了一次蜕变。" },
    { hanzi: "顿悟", hanViet: "đốn ngộ", pinyin: "dùn wù", meaning: "Đốn ngộ / chợt hiểu", example: "他忽然顿悟了人生真谛。" },
    { hanzi: "哲思", hanViet: "triết tư", pinyin: "zhé sī", meaning: "Suy tư triết học", example: "诗中充满哲思。" },
    { hanzi: "彰显", hanViet: "chương hiển", pinyin: "zhāng xiǎn", meaning: "Thể hiện rõ / tôn vinh", example: "这彰显了他的才华。" },
    { hanzi: "缔造", hanViet: "đế tạo", pinyin: "dì zào", meaning: "Tạo dựng / kiến lập", example: "他们缔造了辉煌历史。" },
    { hanzi: "缘分", hanViet: "duyên phận", pinyin: "yuán fèn", meaning: "Duyên phận / duyên số", example: "我们相遇是一种缘分。" },
    { hanzi: "憧憬", hanViet: "sung cảnh", pinyin: "chōng jǐng", meaning: "Khao khát / mơ về", example: "她对未来充满憧憬。" },
    { hanzi: "眷恋", hanViet: "quyến luyến", pinyin: "juàn liàn", meaning: "Quyến luyến / lưu luyến", example: "他眷恋着故乡的一切。" },
    { hanzi: "惆怅", hanViet: "trù trướng", pinyin: "chóu chàng", meaning: "Bâng khuâng / man mác buồn", example: "离别时心中一阵惆怅。" },
    { hanzi: "释怀", hanViet: "thích hoài", pinyin: "shì huái", meaning: "Buông bỏ / nguôi ngoai", example: "过去的事就释怀吧。" },
    { hanzi: "邂逅", hanViet: "giải cấu", pinyin: "xiè hòu", meaning: "Tình cờ gặp gỡ", example: "一场美丽的邂逅改变了他。" },
    { hanzi: "沧桑", hanViet: "thương tang", pinyin: "cāng sāng", meaning: "Dâu bể / thăng trầm", example: "他的脸上写满了沧桑。" },
    { hanzi: "婉转", hanViet: "uyển chuyển", pinyin: "wǎn zhuǎn", meaning: "Uyển chuyển / du dương", example: "她说话很婉转。" },
    { hanzi: "静谧", hanViet: "tĩnh mật", pinyin: "jìng mì", meaning: "Tĩnh mịch / yên ả", example: "静谧的夜晚适合思考。" },
    { hanzi: "璀璨", hanViet: "thôi xán", pinyin: "cuǐ càn", meaning: "Rực rỡ / lấp lánh", example: "夜空中星光璀璨。" },
    { hanzi: "守望", hanViet: "thủ vọng", pinyin: "shǒu wàng", meaning: "Trông giữ / ngóng đợi", example: "母亲在门口守望着孩子回家。" },
  { hanzi: "朦胧", hanViet: "mông lung", pinyin: "méng lóng", meaning: "Mờ ảo / mông lung", example: "月光下一切都很朦胧。" },
  { hanzi: "涟漪", hanViet: "liên y", pinyin: "lián yī", meaning: "Gợn sóng (cả nghĩa bóng)", example: "他的话在我心里泛起涟漪。" },
  { hanzi: "斑驳", hanViet: "ban bác", pinyin: "bān bó", meaning: "Loang lổ (ánh sáng, màu)", example: "阳光透过树叶，光影斑驳。" },
  { hanzi: "苍茫", hanViet: "thương mang", pinyin: "cāng máng", meaning: "Mênh mông mờ mịt", example: "暮色苍茫，群山静默。" },
  { hanzi: "缥缈", hanViet: "phiêu miễu", pinyin: "piāo miǎo", meaning: "Hư ảo xa xăm", example: "远处的山在云中显得缥缈。" },
  { hanzi: "巅峰", hanViet: "điên phong", pinyin: "diān fēng", meaning: "Đỉnh cao", example: "他正处于事业的巅峰。" },
  { hanzi: "轨迹", hanViet: "quỹ tích", pinyin: "guǐ jì", meaning: "Quỹ đạo / dấu vết cuộc đời", example: "每个人都有自己的人生轨迹。" },
  { hanzi: "烙印", hanViet: "lạc ấn", pinyin: "lào yìn", meaning: "Dấu ấn khắc sâu", example: "童年给我留下深深的烙印。" },
  { hanzi: "羁绊", hanViet: "ky bạn", pinyin: "jī bàn", meaning: "Ràng buộc / gắn kết", example: "家人之间有割不断的羁绊。" },
  { hanzi: "执着", hanViet: "chấp trước", pinyin: "zhí zhuó", meaning: "Kiên trì đến cùng / cố chấp", example: "他对梦想非常执着。" },
  { hanzi: "淡然", hanViet: "đạm nhiên", pinyin: "dàn rán", meaning: "Bình thản", example: "面对失败，他很淡然。" },
  { hanzi: "从容", hanViet: "thung dung", pinyin: "cóng róng", meaning: "Ung dung", example: "她从容地走上舞台。" },
  { hanzi: "豁达", hanViet: "khoát đạt", pinyin: "huò dá", meaning: "Rộng lượng phóng khoáng", example: "豁达的人活得更快乐。" },
  { hanzi: "洒脱", hanViet: "sái thoát", pinyin: "sǎ tuō", meaning: "Phóng khoáng tự nhiên", example: "他活得很洒脱。" },
  { hanzi: "坦荡", hanViet: "thản đãng", pinyin: "tǎn dàng", meaning: "Quang minh chính đại", example: "做人要坦荡。" },
  { hanzi: "静默", hanViet: "tĩnh mặc", pinyin: "jìng mò", meaning: "Lặng im", example: "全场静默了一分钟。" },
  { hanzi: "沉思", hanViet: "trầm tư", pinyin: "chén sī", meaning: "Trầm tư", example: "他望着窗外陷入沉思。" },
  { hanzi: "凝望", hanViet: "ngưng vọng", pinyin: "níng wàng", meaning: "Nhìn chăm chú (xa xăm)", example: "她凝望着远方的灯火。" },
  { hanzi: "眺望", hanViet: "thiếu vọng", pinyin: "tiào wàng", meaning: "Phóng tầm mắt nhìn xa", example: "站在山顶眺望整座城市。" },
  { hanzi: "守护", hanViet: "thủ hộ", pinyin: "shǒu hù", meaning: "Bảo vệ / canh giữ", example: "母亲默默守护着孩子。" },
  { hanzi: "牵挂", hanViet: "khiên quải", pinyin: "qiān guà", meaning: "Vương vấn lo lắng", example: "离家再远也牵挂父母。" },
  { hanzi: "思绪", hanViet: "tư tự", pinyin: "sī xù", meaning: "Dòng suy nghĩ", example: "夜深了，思绪万千。" },
  { hanzi: "心扉", hanViet: "tâm phi", pinyin: "xīn fēi", meaning: "Cánh cửa tâm hồn", example: "音乐打开了我的心扉。" },
  { hanzi: "韶华", hanViet: "thiều hoa", pinyin: "sháo huá", meaning: "Tuổi xuân tươi đẹp", example: "莫负韶华，努力前行。" },
  { hanzi: "流年", hanViet: "lưu niên", pinyin: "liú nián", meaning: "Năm tháng trôi qua", example: "似水流年，转眼十年。" },
  { hanzi: "浮生", hanViet: "phù sinh", pinyin: "fú shēng", meaning: "Kiếp phù sinh", example: "偷得浮生半日闲。" },
  { hanzi: "尘世", hanViet: "trần thế", pinyin: "chén shì", meaning: "Cõi trần", example: "远离尘世的喧嚣。" },
  { hanzi: "彼岸", hanViet: "bỉ ngạn", pinyin: "bǐ àn", meaning: "Bờ bên kia (lý tưởng)", example: "梦想在彼岸等着我们。" },
  { hanzi: "归宿", hanViet: "quy túc", pinyin: "guī sù", meaning: "Bến đỗ / nơi thuộc về", example: "家是心灵的归宿。" },
  { hanzi: "婉约", hanViet: "uyển ước", pinyin: "wǎn yuē", meaning: "Dịu dàng kín đáo (văn phong)", example: "她的文字很婉约。" },
];
