/** Kho từ HSK1 (150 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK1: HSKWord[] = [
    { hanzi: "你好", hanViet: "nhĩ hảo", pinyin: "nǐ hǎo", meaning: "Xin chào", example: "你好，我叫小明。" },
    { hanzi: "谢谢", hanViet: "tạ tạ", pinyin: "xiè xiè", meaning: "Cảm ơn", example: "谢谢你的帮助！" },
    { hanzi: "再见", hanViet: "tái kiến", pinyin: "zài jiàn", meaning: "Tạm biệt", example: "明天见，再见！" },
    { hanzi: "我", hanViet: "ngã", pinyin: "wǒ", meaning: "Tôi / tao", example: "我是学生。" },
    { hanzi: "你", hanViet: "nhĩ", pinyin: "nǐ", meaning: "Bạn / mày", example: "你叫什么名字？" },
    { hanzi: "他", hanViet: "tha", pinyin: "tā", meaning: "Anh ấy / ông ấy", example: "他是我的朋友。" },
    { hanzi: "她", hanViet: "tha", pinyin: "tā", meaning: "Cô ấy / bà ấy", example: "她很漂亮。" },
    { hanzi: "爱", hanViet: "ái", pinyin: "ài", meaning: "Yêu / tình yêu", example: "我爱你。" },
    { hanzi: "家", hanViet: "gia", pinyin: "jiā", meaning: "Gia đình / nhà", example: "我的家很小。" },
    { hanzi: "朋友", hanViet: "bằng hữu", pinyin: "péng yǒu", meaning: "Bạn bè", example: "她是我最好的朋友。" },
    { hanzi: "学生", hanViet: "học sinh", pinyin: "xué shēng", meaning: "Học sinh", example: "他是一名好学生。" },
    { hanzi: "老师", hanViet: "lão sư", pinyin: "lǎo shī", meaning: "Giáo viên", example: "老师对我们很好。" },
    { hanzi: "中国", hanViet: "trung quốc", pinyin: "zhōng guó", meaning: "Trung Quốc", example: "我来自中国。" },
    { hanzi: "汉语", hanViet: "hán ngữ", pinyin: "hàn yǔ", meaning: "Tiếng Trung", example: "我在学汉语。" },
    { hanzi: "水", hanViet: "thủy", pinyin: "shuǐ", meaning: "Nước", example: "我想喝水。" },
    { hanzi: "吃", hanViet: "cật", pinyin: "chī", meaning: "Ăn", example: "我们去吃饭吧。" },
    { hanzi: "喝", hanViet: "hát", pinyin: "hē", meaning: "Uống", example: "你想喝什么？" },
    { hanzi: "好", hanViet: "hảo", pinyin: "hǎo", meaning: "Tốt / được", example: "这个主意很好。" },
    { hanzi: "大", hanViet: "đại", pinyin: "dà", meaning: "To / lớn", example: "那栋楼很大。" },
    { hanzi: "小", hanViet: "tiểu", pinyin: "xiǎo", meaning: "Nhỏ / bé", example: "这只猫很小。" },
    { hanzi: "妈妈", hanViet: "ma ma", pinyin: "mā ma", meaning: "Mẹ", example: "我爱我的妈妈。" },
    { hanzi: "爸爸", hanViet: "bá bá", pinyin: "bà ba", meaning: "Bố", example: "爸爸在工作。" },
    { hanzi: "学校", hanViet: "học hiệu", pinyin: "xué xiào", meaning: "Trường học", example: "我们的学校很大。" },
    { hanzi: "今天", hanViet: "kim thiên", pinyin: "jīn tiān", meaning: "Hôm nay", example: "今天天气很好。" },
    { hanzi: "明天", hanViet: "minh thiên", pinyin: "míng tiān", meaning: "Ngày mai", example: "明天见！" },
    { hanzi: "名字", hanViet: "danh tự", pinyin: "míng zi", meaning: "Tên", example: "你叫什么名字？" },
    { hanzi: "看", hanViet: "khán", pinyin: "kàn", meaning: "Xem / nhìn", example: "我喜欢看书。" },
    { hanzi: "听", hanViet: "thính", pinyin: "tīng", meaning: "Nghe", example: "我在听音乐。" },
    { hanzi: "茶", hanViet: "trà", pinyin: "chá", meaning: "Trà", example: "请喝茶。" },
    { hanzi: "高兴", hanViet: "cao hứng", pinyin: "gāo xìng", meaning: "Vui mừng", example: "认识你很高兴。" },
    { hanzi: "是", hanViet: "thị", pinyin: "shì", meaning: "Là", example: "我是学生。" },
    { hanzi: "不", hanViet: "bất", pinyin: "bù", meaning: "Không", example: "我不知道。" },
    { hanzi: "在", hanViet: "tại", pinyin: "zài", meaning: "Ở / đang", example: "他在家。" },
    { hanzi: "有", hanViet: "hữu", pinyin: "yǒu", meaning: "Có", example: "我有一只猫。" },
    { hanzi: "人", hanViet: "nhân", pinyin: "rén", meaning: "Người", example: "他是好人。" },
    { hanzi: "这", hanViet: "giá", pinyin: "zhè", meaning: "Này / đây", example: "这是我的书。" },
    { hanzi: "那", hanViet: "na", pinyin: "nà", meaning: "Kia / đó", example: "那是什么？" },
    { hanzi: "什么", hanViet: "thậm ma", pinyin: "shén me", meaning: "Cái gì", example: "你想吃什么？" },
    { hanzi: "谁", hanViet: "thùy", pinyin: "shéi", meaning: "Ai", example: "他是谁？" },
    { hanzi: "哪儿", hanViet: "na nhi", pinyin: "nǎr", meaning: "Ở đâu", example: "你在哪儿？" },
    { hanzi: "几", hanViet: "kỷ", pinyin: "jǐ", meaning: "Mấy", example: "现在几点？" },
    { hanzi: "多少", hanViet: "đa thiểu", pinyin: "duō shao", meaning: "Bao nhiêu", example: "这个多少钱？" },
    { hanzi: "岁", hanViet: "tuế", pinyin: "suì", meaning: "Tuổi", example: "你几岁了？" },
    { hanzi: "书", hanViet: "thư", pinyin: "shū", meaning: "Sách", example: "我喜欢看书。" },
    { hanzi: "字", hanViet: "tự", pinyin: "zì", meaning: "Chữ", example: "这个字怎么读？" },
    { hanzi: "钱", hanViet: "tiền", pinyin: "qián", meaning: "Tiền", example: "我没有钱。" },
    { hanzi: "飞机", hanViet: "phi cơ", pinyin: "fēi jī", meaning: "Máy bay", example: "我坐飞机去北京。" },
    { hanzi: "出租车", hanViet: "xuất tô xa", pinyin: "chū zū chē", meaning: "Taxi", example: "我们坐出租车吧。" },
    { hanzi: "电视", hanViet: "điện thị", pinyin: "diàn shì", meaning: "Tivi", example: "我在看电视。" },
    { hanzi: "电脑", hanViet: "điện não", pinyin: "diàn nǎo", meaning: "Máy tính", example: "我的电脑很新。" },
    { hanzi: "电影", hanViet: "điện ảnh", pinyin: "diàn yǐng", meaning: "Phim", example: "我们去看电影吧。" },
    { hanzi: "米饭", hanViet: "mễ phạn", pinyin: "mǐ fàn", meaning: "Cơm", example: "我想吃米饭。" },
    { hanzi: "苹果", hanViet: "bình quả", pinyin: "píng guǒ", meaning: "Quả táo", example: "我吃了一个苹果。" },
    { hanzi: "菜", hanViet: "thái", pinyin: "cài", meaning: "Món ăn / rau", example: "这个菜很好吃。" },
    { hanzi: "杯子", hanViet: "bôi tử", pinyin: "bēi zi", meaning: "Cái cốc", example: "杯子里有水。" },
    { hanzi: "桌子", hanViet: "trác tử", pinyin: "zhuō zi", meaning: "Cái bàn", example: "书在桌子上。" },
    { hanzi: "椅子", hanViet: "ỷ tử", pinyin: "yǐ zi", meaning: "Cái ghế", example: "请坐在椅子上。" },
    { hanzi: "猫", hanViet: "miêu", pinyin: "māo", meaning: "Con mèo", example: "我家有一只猫。" },
    { hanzi: "狗", hanViet: "cẩu", pinyin: "gǒu", meaning: "Con chó", example: "那只狗很可爱。" },
    { hanzi: "下雨", hanViet: "hạ vũ", pinyin: "xià yǔ", meaning: "Trời mưa", example: "今天下雨了。" },
    { hanzi: "去", hanViet: "khứ", pinyin: "qù", meaning: "Đi / đến (nơi nào đó)", example: "我去学校。" },
    { hanzi: "来", hanViet: "lai", pinyin: "lái", meaning: "Đến / tới", example: "你什么时候来？" },
    { hanzi: "说", hanViet: "thuyết", pinyin: "shuō", meaning: "Nói", example: "请你再说一次。" },
    { hanzi: "写", hanViet: "tả", pinyin: "xiě", meaning: "Viết", example: "我会写汉字。" },
    { hanzi: "坐", hanViet: "tọa", pinyin: "zuò", meaning: "Ngồi / đi (xe)", example: "请坐！" },
    { hanzi: "住", hanViet: "trụ", pinyin: "zhù", meaning: "Ở / sống tại", example: "你住在哪儿？" },
    { hanzi: "买", hanViet: "mãi", pinyin: "mǎi", meaning: "Mua", example: "我想买一本书。" },
    { hanzi: "做", hanViet: "tố", pinyin: "zuò", meaning: "Làm", example: "你在做什么？" },
    { hanzi: "叫", hanViet: "khiếu", pinyin: "jiào", meaning: "Gọi / tên là", example: "我叫小美。" },
    { hanzi: "想", hanViet: "tưởng", pinyin: "xiǎng", meaning: "Muốn / nghĩ / nhớ", example: "我想回家。" },
    { hanzi: "会", hanViet: "hội", pinyin: "huì", meaning: "Biết (kỹ năng) / sẽ", example: "我会说汉语。" },
    { hanzi: "能", hanViet: "năng", pinyin: "néng", meaning: "Có thể", example: "你能帮我吗？" },
    { hanzi: "喜欢", hanViet: "hỉ hoan", pinyin: "xǐ huan", meaning: "Thích", example: "我喜欢喝茶。" },
    { hanzi: "和", hanViet: "hòa", pinyin: "hé", meaning: "Và / với", example: "我和朋友去吃饭。" },
    { hanzi: "医生", hanViet: "y sinh", pinyin: "yī shēng", meaning: "Bác sĩ", example: "他是一名医生。" },
    { hanzi: "儿子", hanViet: "nhi tử", pinyin: "ér zi", meaning: "Con trai", example: "他的儿子三岁了。" },
    { hanzi: "女儿", hanViet: "nữ nhi", pinyin: "nǚ ér", meaning: "Con gái", example: "我女儿很可爱。" },
    { hanzi: "衣服", hanViet: "y phục", pinyin: "yī fu", meaning: "Quần áo", example: "这件衣服很漂亮。" },
    { hanzi: "商店", hanViet: "thương điếm", pinyin: "shāng diàn", meaning: "Cửa hàng", example: "商店里人很多。" },
    { hanzi: "北京", hanViet: "bắc kinh", pinyin: "běi jīng", meaning: "Bắc Kinh", example: "我想去北京。" },
    { hanzi: "年", hanViet: "niên", pinyin: "nián", meaning: "Năm", example: "明年我去中国。" },
    { hanzi: "现在", hanViet: "hiện tại", pinyin: "xiàn zài", meaning: "Bây giờ", example: "现在几点了？" },
    { hanzi: "昨天", hanViet: "tạc thiên", pinyin: "zuó tiān", meaning: "Hôm qua", example: "昨天我很忙。" },
    { hanzi: "冷", hanViet: "lãnh", pinyin: "lěng", meaning: "Lạnh", example: "今天很冷。" },
    { hanzi: "热", hanViet: "nhiệt", pinyin: "rè", meaning: "Nóng", example: "夏天很热。" },
    { hanzi: "多", hanViet: "đa", pinyin: "duō", meaning: "Nhiều", example: "他的朋友很多。" },
    { hanzi: "少", hanViet: "thiểu", pinyin: "shǎo", meaning: "Ít", example: "这儿人很少。" },
    { hanzi: "东西", hanViet: "đông tây", pinyin: "dōng xi", meaning: "Đồ vật / thứ", example: "我要买东西。" },
    { hanzi: "怎么", hanViet: "chẩm ma", pinyin: "zěn me", meaning: "Như thế nào / sao", example: "这个字怎么读？" },
    { hanzi: "请", hanViet: "thỉnh", pinyin: "qǐng", meaning: "Mời / xin", example: "请进，请坐。" },
    { hanzi: "一", hanViet: "nhất", pinyin: "yī", meaning: "Một / số 1", example: "我有一本书。" },
    { hanzi: "二", hanViet: "nhị", pinyin: "èr", meaning: "Hai / số 2", example: "现在是二月。" },
    { hanzi: "三", hanViet: "tam", pinyin: "sān", meaning: "Ba / số 3", example: "我家有三口人。" },
    { hanzi: "四", hanViet: "tứ", pinyin: "sì", meaning: "Bốn / số 4", example: "现在四点了。" },
    { hanzi: "五", hanViet: "ngũ", pinyin: "wǔ", meaning: "Năm / số 5", example: "我五点回家。" },
    { hanzi: "六", hanViet: "lục", pinyin: "liù", meaning: "Sáu / số 6", example: "他六岁了。" },
    { hanzi: "七", hanViet: "thất", pinyin: "qī", meaning: "Bảy / số 7", example: "我们七点吃饭。" },
    { hanzi: "八", hanViet: "bát", pinyin: "bā", meaning: "Tám / số 8", example: "现在八点了。" },
    { hanzi: "九", hanViet: "cửu", pinyin: "jiǔ", meaning: "Chín / số 9", example: "他九岁了。" },
    { hanzi: "十", hanViet: "thập", pinyin: "shí", meaning: "Mười / số 10", example: "我十点睡觉。" },
    { hanzi: "零", hanViet: "linh", pinyin: "líng", meaning: "Số 0", example: "现在是十点零五分。" },
    { hanzi: "个", hanViet: "cá", pinyin: "gè", meaning: "Cái / con (lượng từ chung)", example: "我有一个问题。" },
    { hanzi: "本", hanViet: "bản", pinyin: "běn", meaning: "Quyển / cuốn (lượng từ sách)", example: "这本书很好看。" },
    { hanzi: "块", hanViet: "khối", pinyin: "kuài", meaning: "Đồng (tiền) / miếng", example: "这个十块钱。" },
    { hanzi: "些", hanViet: "ta", pinyin: "xiē", meaning: "Một vài / một số", example: "我买了一些水果。" },
    { hanzi: "的", hanViet: "đích", pinyin: "de", meaning: "Của (trợ từ sở hữu)", example: "这是我的书。" },
    { hanzi: "了", hanViet: "liễu", pinyin: "le", meaning: "Rồi (trợ từ hoàn thành)", example: "他走了。" },
    { hanzi: "吗", hanViet: "ma", pinyin: "ma", meaning: "Không? (trợ từ nghi vấn)", example: "你是学生吗？" },
    { hanzi: "呢", hanViet: "ni", pinyin: "ne", meaning: "Thế còn...? (trợ từ)", example: "我很好，你呢？" },
    { hanzi: "喂", hanViet: "uy", pinyin: "wéi", meaning: "Alô (nghe điện thoại)", example: "喂，你好！" },
    { hanzi: "都", hanViet: "đô", pinyin: "dōu", meaning: "Đều / cả", example: "我们都是学生。" },
    { hanzi: "很", hanViet: "ngận", pinyin: "hěn", meaning: "Rất", example: "今天我很开心。" },
    { hanzi: "太", hanViet: "thái", pinyin: "tài", meaning: "Quá / lắm", example: "太好了！" },
    { hanzi: "没有", hanViet: "một hữu", pinyin: "méi yǒu", meaning: "Không có", example: "我没有时间。" },
    { hanzi: "对不起", hanViet: "đối bất khởi", pinyin: "duì bu qǐ", meaning: "Xin lỗi", example: "对不起，我来晚了。" },
    { hanzi: "没关系", hanViet: "một quan hệ", pinyin: "méi guān xi", meaning: "Không sao", example: "没关系，别担心。" },
    { hanzi: "不客气", hanViet: "bất khách khí", pinyin: "bú kè qi", meaning: "Không có gì (đáp cảm ơn)", example: "不客气，这是我应该做的。" },
    { hanzi: "我们", hanViet: "ngã môn", pinyin: "wǒ men", meaning: "Chúng tôi / chúng ta", example: "我们是好朋友。" },
    { hanzi: "它", hanViet: "tha", pinyin: "tā", meaning: "Nó (đồ vật / con vật)", example: "它是我的猫。" },
    { hanzi: "先生", hanViet: "tiên sinh", pinyin: "xiān sheng", meaning: "Ông / ngài / chồng", example: "王先生在家吗？" },
    { hanzi: "小姐", hanViet: "tiểu thư", pinyin: "xiǎo jiě", meaning: "Cô (gọi phụ nữ trẻ)", example: "李小姐是老师。" },
    { hanzi: "月", hanViet: "nguyệt", pinyin: "yuè", meaning: "Tháng / mặt trăng", example: "我五月去北京。" },
    { hanzi: "日", hanViet: "nhật", pinyin: "rì", meaning: "Ngày / mặt trời", example: "今天是六月一日。" },
    { hanzi: "号", hanViet: "hiệu", pinyin: "hào", meaning: "Ngày (trong tháng) / số", example: "今天几号？" },
    { hanzi: "点", hanViet: "điểm", pinyin: "diǎn", meaning: "Giờ (thời gian)", example: "现在三点了。" },
    { hanzi: "分钟", hanViet: "phân chung", pinyin: "fēn zhōng", meaning: "Phút", example: "等我五分钟。" },
    { hanzi: "星期", hanViet: "tinh kỳ", pinyin: "xīng qī", meaning: "Tuần / thứ", example: "今天星期几？" },
    { hanzi: "时候", hanViet: "thời hậu", pinyin: "shí hou", meaning: "Lúc / khi", example: "你什么时候来？" },
    { hanzi: "上午", hanViet: "thượng ngọ", pinyin: "shàng wǔ", meaning: "Buổi sáng", example: "我上午有课。" },
    { hanzi: "中午", hanViet: "trung ngọ", pinyin: "zhōng wǔ", meaning: "Buổi trưa", example: "中午一起吃饭吧。" },
    { hanzi: "下午", hanViet: "hạ ngọ", pinyin: "xià wǔ", meaning: "Buổi chiều", example: "下午我去商店。" },
    { hanzi: "上", hanViet: "thượng", pinyin: "shàng", meaning: "Trên / lên", example: "书在桌子上。" },
    { hanzi: "下", hanViet: "hạ", pinyin: "xià", meaning: "Dưới / xuống", example: "猫在椅子下。" },
    { hanzi: "里", hanViet: "lý", pinyin: "lǐ", meaning: "Trong / bên trong", example: "他在家里。" },
    { hanzi: "前面", hanViet: "tiền diện", pinyin: "qián miàn", meaning: "Phía trước", example: "学校在前面。" },
    { hanzi: "后面", hanViet: "hậu diện", pinyin: "hòu miàn", meaning: "Phía sau", example: "商店在医院后面。" },
    { hanzi: "这儿", hanViet: "giá nhi", pinyin: "zhèr", meaning: "Ở đây", example: "请来这儿坐。" },
    { hanzi: "那儿", hanViet: "na nhi", pinyin: "nàr", meaning: "Ở kia / ở đó", example: "他在那儿等你。" },
    { hanzi: "回", hanViet: "hồi", pinyin: "huí", meaning: "Về / quay lại", example: "我想回家。" },
    { hanzi: "开", hanViet: "khai", pinyin: "kāi", meaning: "Mở / lái (xe)", example: "请开门。" },
    { hanzi: "认识", hanViet: "nhận thức", pinyin: "rèn shi", meaning: "Quen biết / biết", example: "认识你很高兴。" },
    { hanzi: "电话", hanViet: "điện thoại", pinyin: "diàn huà", meaning: "Điện thoại", example: "我给你打电话。" },
    { hanzi: "火车站", hanViet: "hỏa xa trạm", pinyin: "huǒ chē zhàn", meaning: "Ga tàu hỏa", example: "火车站离这儿很远。" },
    { hanzi: "饭店", hanViet: "phạn điếm", pinyin: "fàn diàn", meaning: "Nhà hàng / khách sạn", example: "这家饭店的菜很好吃。" },
    { hanzi: "同学", hanViet: "đồng học", pinyin: "tóng xué", meaning: "Bạn cùng lớp", example: "他是我的同学。" },
    { hanzi: "水果", hanViet: "thủy quả", pinyin: "shuǐ guǒ", meaning: "Hoa quả / trái cây", example: "多吃水果对身体好。" },
    { hanzi: "鱼", hanViet: "ngư", pinyin: "yú", meaning: "Cá", example: "我喜欢吃鱼。" },
    { hanzi: "大学", hanViet: "đại học", pinyin: "dà xué", meaning: "Đại học", example: "我哥哥在大学学习。" },
    { hanzi: "怎么样", hanViet: "chẩm ma dạng", pinyin: "zěn me yàng", meaning: "Thế nào / ra sao", example: "这本书怎么样？" },
    { hanzi: "雨", hanViet: "vũ", pinyin: "yǔ", meaning: "Mưa", example: "雨下得很大。" },
];
