/** Kho từ HSK4 (60 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK4: HSKWord[] = [
    { hanzi: "责任", hanViet: "trách nhiệm", pinyin: "zé rèn", meaning: "Trách nhiệm", example: "每个人都有责任。" },
    { hanzi: "尊重", hanViet: "tôn trọng", pinyin: "zūn zhòng", meaning: "Tôn trọng", example: "我们要尊重他人。" },
    { hanzi: "诚实", hanViet: "thành thật", pinyin: "chéng shí", meaning: "Thành thật", example: "诚实是最重要的品质。" },
    { hanzi: "勇气", hanViet: "dũng khí", pinyin: "yǒng qì", meaning: "Dũng cảm / can đảm", example: "改变需要勇气。" },
    { hanzi: "智慧", hanViet: "trí tuệ", pinyin: "zhì huì", meaning: "Trí tuệ / sự khôn ngoan", example: "智慧比知识更重要。" },
    { hanzi: "坚持", hanViet: "kiên trì", pinyin: "jiān chí", meaning: "Kiên trì / bền vững", example: "坚持就是胜利。" },
    { hanzi: "创造", hanViet: "sáng tạo", pinyin: "chuàng zào", meaning: "Sáng tạo", example: "艺术家创造了美好的作品。" },
    { hanzi: "想象", hanViet: "tưởng tượng", pinyin: "xiǎng xiàng", meaning: "Tưởng tượng", example: "孩子的想象力很丰富。" },
    { hanzi: "分析", hanViet: "phân tích", pinyin: "fēn xī", meaning: "Phân tích", example: "我们需要分析数据。" },
    { hanzi: "解决", hanViet: "giải quyết", pinyin: "jiě jué", meaning: "Giải quyết", example: "我们要解决这个问题。" },
    { hanzi: "合作", hanViet: "hợp tác", pinyin: "hé zuò", meaning: "Hợp tác", example: "合作才能共赢。" },
    { hanzi: "批评", hanViet: "phê bình", pinyin: "pī píng", meaning: "Phê bình / chỉ trích", example: "接受批评需要勇气。" },
    { hanzi: "忍耐", hanViet: "nhẫn nại", pinyin: "rěn nài", meaning: "Kiên nhẫn / chịu đựng", example: "成功需要忍耐。" },
    { hanzi: "谦虚", hanViet: "khiêm hư", pinyin: "qiān xū", meaning: "Khiêm tốn", example: "他是一个谦虚的人。" },
    { hanzi: "矛盾", hanViet: "mâu thuẫn", pinyin: "máo dùn", meaning: "Mâu thuẫn", example: "他内心充满矛盾。" },
    { hanzi: "复杂", hanViet: "phức tạp", pinyin: "fù zá", meaning: "Phức tạp", example: "这个问题很复杂。" },
    { hanzi: "逻辑", hanViet: "la tập", pinyin: "luó jí", meaning: "Logic / lý luận", example: "他的思维很有逻辑。" },
    { hanzi: "赞美", hanViet: "tán mỹ", pinyin: "zàn měi", meaning: "Khen ngợi / ca ngợi", example: "大家都赞美他的作品。" },
    { hanzi: "哲学", hanViet: "triết học", pinyin: "zhé xué", meaning: "Triết học", example: "我喜欢读哲学书。" },
    { hanzi: "价值观", hanViet: "giá trị quan", pinyin: "jià zhí guān", meaning: "Quan điểm giá trị", example: "每个人的价值观不同。" },
    { hanzi: "幸福", hanViet: "hạnh phúc", pinyin: "xìng fú", meaning: "Hạnh phúc", example: "和家人在一起很幸福。" },
    { hanzi: "孤独", hanViet: "cô độc", pinyin: "gū dú", meaning: "Cô đơn", example: "一个人也不觉得孤独。" },
    { hanzi: "回忆", hanViet: "hồi ức", pinyin: "huí yì", meaning: "Hồi ức / kỷ niệm", example: "童年的回忆很美好。" },
    { hanzi: "温暖", hanViet: "ôn noãn", pinyin: "wēn nuǎn", meaning: "Ấm áp", example: "你的话让我很温暖。" },
    { hanzi: "浪漫", hanViet: "lãng mạn", pinyin: "làng màn", meaning: "Lãng mạn", example: "这是一个浪漫的故事。" },
    { hanzi: "遗憾", hanViet: "di hám", pinyin: "yí hàn", meaning: "Tiếc nuối", example: "没去成，真遗憾。" },
    { hanzi: "鼓励", hanViet: "cổ lệ", pinyin: "gǔ lì", meaning: "Khích lệ / động viên", example: "谢谢你的鼓励。" },
    { hanzi: "感激", hanViet: "cảm kích", pinyin: "gǎn jī", meaning: "Cảm kích / biết ơn", example: "我非常感激你的帮助。" },
    { hanzi: "青春", hanViet: "thanh xuân", pinyin: "qīng chūn", meaning: "Tuổi thanh xuân", example: "青春只有一次。" },
    { hanzi: "成长", hanViet: "thành trưởng", pinyin: "chéng zhǎng", meaning: "Trưởng thành / lớn lên", example: "困难让我们成长。" },
  { hanzi: "适应", hanViet: "thích ứng", pinyin: "shì yìng", meaning: "Thích nghi", example: "我已经适应了新环境。" },
  { hanzi: "态度", hanViet: "thái độ", pinyin: "tài du", meaning: "Thái độ", example: "他的态度很认真。" },
  { hanzi: "经历", hanViet: "kinh lịch", pinyin: "jīng lì", meaning: "Trải nghiệm / từng trải", example: "这段经历让我成长了很多。" },
  { hanzi: "目标", hanViet: "mục tiêu", pinyin: "mù biāo", meaning: "Mục tiêu", example: "今年我的目标是通过HSK4。" },
  { hanzi: "计划", hanViet: "kế hoạch", pinyin: "jì huà", meaning: "Kế hoạch", example: "你有什么学习计划？" },
  { hanzi: "方法", hanViet: "phương pháp", pinyin: "fāng fǎ", meaning: "Phương pháp", example: "好的方法让学习更轻松。" },
  { hanzi: "信息", hanViet: "tín tức", pinyin: "xìn xī", meaning: "Thông tin", example: "网上有很多有用的信息。" },
  { hanzi: "知识", hanViet: "tri thức", pinyin: "zhī shi", meaning: "Kiến thức", example: "读书让人增长知识。" },
  { hanzi: "能力", hanViet: "năng lực", pinyin: "néng lì", meaning: "Năng lực", example: "他的工作能力很强。" },
  { hanzi: "性格", hanViet: "tính cách", pinyin: "xìng gé", meaning: "Tính cách", example: "她的性格很开朗。" },
  { hanzi: "情况", hanViet: "tình huống", pinyin: "qíng kuàng", meaning: "Tình hình", example: "请告诉我具体情况。" },
  { hanzi: "区别", hanViet: "khu biệt", pinyin: "qū bié", meaning: "Sự khác biệt", example: "这两个词有什么区别？" },
  { hanzi: "优点", hanViet: "ưu điểm", pinyin: "yōu diǎn", meaning: "Ưu điểm", example: "每个人都有自己的优点。" },
  { hanzi: "缺点", hanViet: "khuyết điểm", pinyin: "quē diǎn", meaning: "Khuyết điểm", example: "不要害怕承认缺点。" },
  { hanzi: "标准", hanViet: "tiêu chuẩn", pinyin: "biāo zhǔn", meaning: "Tiêu chuẩn", example: "他的发音很标准。" },
  { hanzi: "条件", hanViet: "điều kiện", pinyin: "tiáo jiàn", meaning: "Điều kiện", example: "这里的学习条件很好。" },
  { hanzi: "结果", hanViet: "kết quả", pinyin: "jié guǒ", meaning: "Kết quả", example: "考试结果明天出来。" },
  { hanzi: "原因", hanViet: "nguyên nhân", pinyin: "yuán yīn", meaning: "Nguyên nhân", example: "迟到的原因是堵车。" },
  { hanzi: "意见", hanViet: "ý kiến", pinyin: "yì jiàn", meaning: "Ý kiến", example: "我想听听你的意见。" },
  { hanzi: "建议", hanViet: "kiến nghị", pinyin: "jiàn yì", meaning: "Đề xuất / gợi ý", example: "我建议你早点儿开始准备。" },
  { hanzi: "讨论", hanViet: "thảo luận", pinyin: "tǎo lùn", meaning: "Thảo luận", example: "我们讨论一下这个问题吧。" },
  { hanzi: "研究", hanViet: "nghiên cứu", pinyin: "yán jiū", meaning: "Nghiên cứu", example: "他在研究中国文化。" },
  { hanzi: "管理", hanViet: "quản lý", pinyin: "guǎn lǐ", meaning: "Quản lý", example: "学会管理自己的时间。" },
  { hanzi: "竞争", hanViet: "cạnh tranh", pinyin: "jìng zhēng", meaning: "Cạnh tranh", example: "现在的竞争很激烈。" },
  { hanzi: "交流", hanViet: "giao lưu", pinyin: "jiāo liú", meaning: "Giao lưu / trao đổi", example: "多和中国朋友交流。" },
  { hanzi: "支持", hanViet: "chi trì", pinyin: "zhī chí", meaning: "Ủng hộ", example: "谢谢你一直支持我。" },
  { hanzi: "拒绝", hanViet: "cự tuyệt", pinyin: "jù jué", meaning: "Từ chối", example: "他拒绝了我的邀请。" },
  { hanzi: "怀疑", hanViet: "hoài nghi", pinyin: "huái yí", meaning: "Nghi ngờ", example: "我怀疑这个消息不是真的。" },
  { hanzi: "羡慕", hanViet: "tiện mộ", pinyin: "xiàn mù", meaning: "Ngưỡng mộ / ghen tị", example: "大家都羡慕他的好运气。" },
  { hanzi: "后悔", hanViet: "hậu hối", pinyin: "hòu huǐ", meaning: "Hối hận", example: "我后悔没有早点儿学汉语。" },
];
