/** Kho từ HSK5 (60 từ) — tách từ hsk-data.ts (đợt 20) để dễ mở rộng từng cấp. */
import type { HSKWord } from "./types";

export const HSK5: HSKWord[] = [
    { hanzi: "本质", hanViet: "bản chất", pinyin: "běn zhì", meaning: "Bản chất", example: "要看清事物的本质。" },
    { hanzi: "规律", hanViet: "quy luật", pinyin: "guī lǜ", meaning: "Quy luật", example: "自然界有其规律。" },
    { hanzi: "意识", hanViet: "ý thức", pinyin: "yì shí", meaning: "Ý thức / nhận thức", example: "要有环保意识。" },
    { hanzi: "创新", hanViet: "sáng tân", pinyin: "chuàng xīn", meaning: "Sáng tạo / đổi mới", example: "创新是发展的动力。" },
    { hanzi: "突破", hanViet: "đột phá", pinyin: "tū pò", meaning: "Đột phá / vượt qua", example: "科技有了新的突破。" },
    { hanzi: "探索", hanViet: "thám sách", pinyin: "tàn suǒ", meaning: "Khám phá / tìm tòi", example: "人类不断探索宇宙。" },
    { hanzi: "超越", hanViet: "siêu việt", pinyin: "chāo yuè", meaning: "Vượt qua / siêu việt", example: "不断超越自我。" },
    { hanzi: "境界", hanViet: "cảnh giới", pinyin: "jìng jiè", meaning: "Cảnh giới / tầm mức", example: "艺术达到了新的境界。" },
    { hanzi: "升华", hanViet: "thăng hoa", pinyin: "shēng huá", meaning: "Thăng hoa / nâng cao", example: "情感在音乐中升华。" },
    { hanzi: "感悟", hanViet: "cảm ngộ", pinyin: "gǎn wù", meaning: "Cảm ngộ / thấu hiểu", example: "生活的感悟很深刻。" },
    { hanzi: "辩证", hanViet: "biện chứng", pinyin: "biàn zhèng", meaning: "Biện chứng", example: "要辩证地看问题。" },
    { hanzi: "抽象", hanViet: "trừu tượng", pinyin: "chōu xiàng", meaning: "Trừu tượng", example: "这个概念很抽象。" },
    { hanzi: "启示", hanViet: "khải thị", pinyin: "qǐ shì", meaning: "Bài học / khải thị", example: "这件事给了我很大启示。" },
    { hanzi: "观念", hanViet: "quan niệm", pinyin: "guān niàn", meaning: "Quan niệm / khái niệm", example: "传统观念影响着我们。" },
    { hanzi: "批判", hanViet: "phê phán", pinyin: "pī pàn", meaning: "Phê phán", example: "批判性思维很重要。" },
    { hanzi: "推断", hanViet: "suy đoán", pinyin: "tuī duàn", meaning: "Suy luận / suy đoán", example: "根据证据推断结论。" },
    { hanzi: "假设", hanViet: "giả thiết", pinyin: "jiǎ shè", meaning: "Giả thuyết / giả định", example: "科学研究需要假设。" },
    { hanzi: "验证", hanViet: "nghiệm chứng", pinyin: "yàn zhèng", meaning: "Kiểm chứng / xác nhận", example: "用实验验证假设。" },
    { hanzi: "统一", hanViet: "thống nhất", pinyin: "tǒng yī", meaning: "Thống nhất", example: "对立统一是自然规律。" },
    { hanzi: "涌现", hanViet: "dũng hiện", pinyin: "yǒng xiàn", meaning: "Xuất hiện ồ ạt / nảy sinh", example: "新思想不断涌现。" },
    { hanzi: "命运", hanViet: "mệnh vận", pinyin: "mìng yùn", meaning: "Số phận / vận mệnh", example: "命运掌握在自己手中。" },
    { hanzi: "灵魂", hanViet: "linh hồn", pinyin: "líng hún", meaning: "Linh hồn / tâm hồn", example: "音乐触动了我的灵魂。" },
    { hanzi: "寂寞", hanViet: "tịch mịch", pinyin: "jì mò", meaning: "Cô quạnh / hiu quạnh", example: "夜深了，他感到寂寞。" },
    { hanzi: "思念", hanViet: "tư niệm", pinyin: "sī niàn", meaning: "Nhớ nhung", example: "我很思念远方的家人。" },
    { hanzi: "珍惜", hanViet: "trân tích", pinyin: "zhēn xī", meaning: "Trân trọng", example: "珍惜眼前人。" },
    { hanzi: "拥抱", hanViet: "ủng bão", pinyin: "yōng bào", meaning: "Ôm / vòng tay", example: "给我一个拥抱吧。" },
    { hanzi: "陪伴", hanViet: "bồi bạn", pinyin: "péi bàn", meaning: "Bầu bạn / đồng hành", example: "陪伴是最长情的告白。" },
    { hanzi: "牺牲", hanViet: "hy sinh", pinyin: "xī shēng", meaning: "Hy sinh", example: "母亲为家庭牺牲了很多。" },
    { hanzi: "永恒", hanViet: "vĩnh hằng", pinyin: "yǒng héng", meaning: "Vĩnh hằng / mãi mãi", example: "真爱是永恒的。" },
    { hanzi: "奇迹", hanViet: "kỳ tích", pinyin: "qí jì", meaning: "Kỳ tích / phép màu", example: "坚持创造奇迹。" },
  { hanzi: "趋势", hanViet: "xu thế", pinyin: "qū shì", meaning: "Xu hướng", example: "学汉语是一种趋势。" },
  { hanzi: "资源", hanViet: "tư nguyên", pinyin: "zī yuán", meaning: "Tài nguyên / nguồn lực", example: "时间是最宝贵的资源。" },
  { hanzi: "效率", hanViet: "hiệu suất", pinyin: "xiào lǜ", meaning: "Hiệu suất", example: "早上学习效率最高。" },
  { hanzi: "利益", hanViet: "lợi ích", pinyin: "lì yì", meaning: "Lợi ích", example: "不能只考虑自己的利益。" },
  { hanzi: "风险", hanViet: "phong hiểm", pinyin: "fēng xiǎn", meaning: "Rủi ro", example: "投资有风险。" },
  { hanzi: "危机", hanViet: "nguy cơ", pinyin: "wēi jī", meaning: "Khủng hoảng", example: "危机也是机会。" },
  { hanzi: "策略", hanViet: "sách lược", pinyin: "cè lüè", meaning: "Chiến lược", example: "学习需要好的策略。" },
  { hanzi: "措施", hanViet: "thố thi", pinyin: "cuò shī", meaning: "Biện pháp", example: "公司采取了新措施。" },
  { hanzi: "范围", hanViet: "phạm vi", pinyin: "fàn wéi", meaning: "Phạm vi", example: "这不在考试范围内。" },
  { hanzi: "角度", hanViet: "giác độ", pinyin: "jiǎo dù", meaning: "Góc độ", example: "换个角度看问题。" },
  { hanzi: "程度", hanViet: "trình độ", pinyin: "chéng dù", meaning: "Mức độ / trình độ", example: "他的汉语达到了很高的程度。" },
  { hanzi: "现象", hanViet: "hiện tượng", pinyin: "xiàn xiàng", meaning: "Hiện tượng", example: "这是一种很普遍的现象。" },
  { hanzi: "规模", hanViet: "quy mô", pinyin: "guī mó", meaning: "Quy mô", example: "这家公司规模很大。" },
  { hanzi: "背景", hanViet: "bối cảnh", pinyin: "bèi jǐng", meaning: "Bối cảnh", example: "了解文化背景很重要。" },
  { hanzi: "基础", hanViet: "cơ sở", pinyin: "jī chǔ", meaning: "Nền tảng", example: "HSK1是汉语的基础。" },
  { hanzi: "核心", hanViet: "hạch tâm", pinyin: "hé xīn", meaning: "Cốt lõi", example: "坚持是成功的核心。" },
  { hanzi: "关键", hanViet: "quan kiện", pinyin: "guān jiàn", meaning: "Then chốt", example: "方法是关键。" },
  { hanzi: "细节", hanViet: "tế tiết", pinyin: "xì jié", meaning: "Chi tiết", example: "细节决定成败。" },
  { hanzi: "印象", hanViet: "ấn tượng", pinyin: "yìn xiàng", meaning: "Ấn tượng", example: "他给我留下了很好的印象。" },
  { hanzi: "气氛", hanViet: "khí phân", pinyin: "qì fēn", meaning: "Bầu không khí", example: "节日的气氛很热闹。" },
  { hanzi: "灵感", hanViet: "linh cảm", pinyin: "líng gǎn", meaning: "Cảm hứng", example: "音乐给我带来灵感。" },
  { hanzi: "魅力", hanViet: "mị lực", pinyin: "mèi lì", meaning: "Sức hút", example: "汉字有独特的魅力。" },
  { hanzi: "智能", hanViet: "trí năng", pinyin: "zhì néng", meaning: "Trí tuệ / thông minh (AI)", example: "人工智能改变了世界。" },
  { hanzi: "道德", hanViet: "đạo đức", pinyin: "dào dé", meaning: "Đạo đức", example: "诚实是基本的道德。" },
  { hanzi: "心理", hanViet: "tâm lý", pinyin: "xīn lǐ", meaning: "Tâm lý", example: "考试前要调整好心理。" },
  { hanzi: "情绪", hanViet: "tình tự", pinyin: "qíng xù", meaning: "Cảm xúc / tâm trạng", example: "学会管理自己的情绪。" },
  { hanzi: "个性", hanViet: "cá tính", pinyin: "gè xìng", meaning: "Cá tính", example: "她是个很有个性的人。" },
  { hanzi: "尊严", hanViet: "tôn nghiêm", pinyin: "zūn yán", meaning: "Phẩm giá", example: "每个人都有自己的尊严。" },
  { hanzi: "信任", hanViet: "tín nhiệm", pinyin: "xìn rèn", meaning: "Tin tưởng", example: "信任需要时间建立。" },
  { hanzi: "宽容", hanViet: "khoan dung", pinyin: "kuān róng", meaning: "Khoan dung", example: "对别人宽容一点儿。" },
];
